services:
  gateway:
    image: ghcr.io/ionaru/deals/gateway:${DEALS_BUILD_TAG:-latest}
    build:
      context: .
      dockerfile: deploy/service.Dockerfile
      args:
        - SERVICE_NAME=gateway
    ports:
      - "3333:3333"
    environment:
      - AUTH_COOKIE_EXPIRY=30
      - AUTH_COOKIE_NAME
      - AUTH_DB_URL
      - AUTH_DB_NAME
      - AUTH_JWT_SECRET
      - COOKIE_SECRET
      - NATS_HOST=nats
      - STORAGE_DB_CA
      - STORAGE_DB_CRT
      - STORAGE_DB_HOST
      - STORAGE_DB_KEY
      - STORAGE_DB_NAME
      - STORAGE_DB_PASS
      - STORAGE_DB_PORT
      - STORAGE_DB_SSL
      - STORAGE_DB_SYNCHRONIZE
      - STORAGE_DB_USER
    depends_on:
      nats:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: 'wget --header="Accept: text/html" localhost:3333/graphql -q --spider'
      start_period: 30s

  client:
    image: ghcr.io/ionaru/deals/client:${DEALS_BUILD_TAG:-latest}
    build:
      context: .
      dockerfile: deploy/client.Dockerfile
    ports:
      - "${DEALS_CLIENT_PORT:-80}:80"
    depends_on:
      gateway:
        condition: service_healthy
    restart: unless-stopped

  nats:
    image: nats:2-alpine
    healthcheck:
      test: "wget localhost:8222/healthz -q --spider"
    restart: always
