interface IDealInformation {
  calculation: (price: number) => number;
  code: string;
  purchaseAmount: number;
}

export enum KruidvatDealType {
  // X + Y
  ONE_PLUS_ONE = 1,
  ONE_PLUS_ONE_DUPLICATE,
  ONE_PLUS_TWO,
  TWO_PLUS_ONE,
  TWO_PLUS_TWO,
  TWO_PLUS_THREE,
  THREE_PLUS_TWO,
  FOUR_PLUS_ONE,
  SIX_PLUS_ONE,

  // 2 for €X
  TWO_FOR_10,
  TWO_FOR_10_95,
  TWO_FOR_11,
  TWO_FOR_12,
  TWO_FOR_13,
  TWO_FOR_18,
  TWO_FOR_2,
  TWO_FOR_2_50,
  TWO_FOR_20,
  TWO_FOR_29_99,
  TWO_FOR_3,
  TWO_FOR_4,
  TWO_FOR_4_49,
  TWO_FOR_4_50,
  TWO_FOR_4_69,
  TWO_FOR_5,
  TWO_FOR_6,
  TWO_FOR_7,
  TWO_FOR_7_50,
  TWO_FOR_8,
  TWO_FOR_9,
  TWO_FOR_9_95,
  TWO_FOR_9_99,
  TWO_FOR_14,
  TWO_FOR_15,
  TWO_FOR_16,
  TWO_FOR_19,
  TWO_FOR_19_99,
  TWO_FOR_22,
  TWO_FOR_24,
  TWO_FOR_25,
  TWO_FOR_27,
  TWO_FOR_28,
  TWO_FOR_65,
  TWO_FOR_75,
  // TWO_FOR_59_99,

  // 3 for €X
  THREE_FOR_10,
  THREE_FOR_10_DUPLICATE,
  THREE_FOR_11,
  THREE_FOR_12,
  THREE_FOR_13,
  THREE_FOR_2,
  THREE_FOR_3,
  THREE_FOR_35,
  THREE_FOR_3_DUPLICATE,
  THREE_FOR_5,
  THREE_FOR_6,
  THREE_FOR_6_50,
  THREE_FOR_7,
  THREE_FOR_7_50,
  THREE_FOR_7_99,
  THREE_FOR_8,
  THREE_FOR_9,
  THREE_FOR_20,
  THREE_FOR_53,
  THREE_FOR_99_99,

  // 4 for €X
  FOUR_FOR_10,
  FOUR_FOR_5,
  FOUR_FOR_6,
  FOUR_FOR_6_99,
  FOUR_FOR_7,
  FOUR_FOR_8,
  FOUR_FOR_9,
  FOUR_FOR_30,
  FOUR_FOR_35,

  // 5 for €X
  FIVE_FOR_3,
  FIVE_FOR_5,
  FIVE_FOR_6,
  FIVE_FOR_10,

  // 6 for €X
  SIX_FOR_7,

  // 8 for €X
  EIGHT_FOR_10,

  // 9 for €X
  NINE_FOR_9_99,

  // X% off
  TEN_PERCENT_OFF,
  FIFTEEN_PERCENT_OFF,
  TWENTY_PERCENT_OFF,
  TWENTY_FIVE_PERCENT_OFF,
  TWENTY_FIVE_PERCENT_EXTRA_OFF,
  THIRTY_PERCENT_OFF,
  THIRTY_THREE_PERCENT_OFF,
  THIRTY_FIVE_PERCENT_OFF,
  FOURTY_PERCENT_OFF,
  FIFTY_PERCENT_OFF,
  FIFTY_FIVE_PERCENT_OFF,
  SIXTY_PERCENT_OFF,
  SIXTY_ONE_PERCENT_OFF,
  SEVENTY_FIVE_PERCENT_EXTRA_OFF,

  // X% off by X amount
  FIFTY_PERCENT_OFF_BY_5,

  // All for €X each
  ALL_FOR_0_99_EACH,
  ALL_FOR_1_29_EACH,
  ALL_FOR_1_50_EACH,
  ALL_FOR_1_EACH,
  ALL_FOR_2_EACH,
  ALL_FOR_29_99_EACH,
  ALL_FOR_2_50_EACH,
  ALL_FOR_2_99_EACH,
  ALL_FOR_3_EACH,
  ALL_FOR_3_99_EACH,
  ALL_FOR_4_EACH,
  ALL_FOR_4_50_EACH,
  ALL_FOR_4_99_EACH,
  ALL_FOR_5_EACH,
  ALL_FOR_6_EACH,
  ALL_FOR_6_50_EACH,
  ALL_FOR_7_EACH,
  ALL_FOR_7_49_EACH,
  ALL_FOR_7_50_EACH,
  ALL_FOR_7_99_EACH,
  ALL_FOR_7_99_EACH_DUPLICATE,
  ALL_FOR_8_99_EACH,
  ALL_FOR_9_EACH,
  ALL_FOR_9_99_EACH,
  ALL_FOR_10_EACH,
  ALL_FOR_12_EACH,
  ALL_FOR_12_50_EACH,
  ALL_FOR_13_EACH,
  ALL_FOR_14_99_EACH,
  ALL_FOR_15_EACH,
  ALL_FOR_16_99_EACH,
  ALL_FOR_17_99_EACH,
  ALL_FOR_18_99_EACH,
  ALL_FOR_19_99_EACH,
  ALL_FOR_20_EACH,
  ALL_FOR_24_99_EACH,
  ALL_FOR_34_99_EACH,
  ALL_FOR_38_99_EACH,
  ALL_FOR_39_99_EACH,
  ALL_FOR_49_99_EACH,

  // All for €X per pack
  ALL_FOR_5_PER_PACK,

  // Second for ...
  SECOND_FOR_ONE,
  SECOND_FOR_TWO,
  SECOND_HALF_PRICE,
  SECOND_HALF_PRICE_DUPLICATE,

  // €X off
  TWO_OFF,
  THREE_OFF,
  FIVE_OFF,
  SIX_OFF,
  NINE_OFF,
  TEN_OFF,
  FIFTEEN_OFF,
  TWENTY_OFF,

  // For X
  FOR_1_49,
  FOR_3,
  FOR_3_99,
  FOR_4_39,
  FOR_4_99,
  FOR_5,
  FOR_5_49,
  FOR_5_75,
  FOR_5_99,
  FOR_6,
  FOR_7_99,
  FOR_8,
  FOR_9,
  FOR_9_99,
  FOR_10,
  FOR_11_99,
  FOR_12_50,
  FOR_13_95,
  FOR_14,
  FOR_14_99,
  FOR_15_99,
  FOR_17_49,
  FOR_24_99,
  FOR_25,
  FOR_26_50,
  FOR_35,
  FPR_45_99,
  FOR_54_99,
  FOR_59_99,
  FOR_69_99,
  FOR_89_99,
  // FOR_109,
  FOR_129_99,
  FOR_249_99,
}

export const kruidvatDealInformation: Record<
  KruidvatDealType,
  IDealInformation
> = Object.freeze({
  [KruidvatDealType.ONE_PLUS_ONE]: {
    calculation: (price: number) => price / 2,
    code: "1003",
    purchaseAmount: 2,
  },
  [KruidvatDealType.ONE_PLUS_ONE_DUPLICATE]: {
    calculation: (price: number) => price / 2,
    code: "5261",
    purchaseAmount: 2,
  },
  [KruidvatDealType.ONE_PLUS_TWO]: {
    calculation: (price: number) => price / 3,
    code: "1467",
    purchaseAmount: 3,
  },
  [KruidvatDealType.TWO_FOR_2]: {
    calculation: () => 2.5 / 2,
    code: "1007",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_2_50]: {
    calculation: () => 1,
    code: "1008",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_3]: {
    calculation: () => 3 / 2,
    code: "1010",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_4]: {
    calculation: () => 4 / 2,
    code: "1013",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_4_49]: {
    calculation: () => 4.49 / 2,
    code: "1202",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_4_50]: {
    calculation: () => 4.5 / 2,
    code: "4291",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_4_69]: {
    calculation: () => 4.69 / 2,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDI4NXxpbWFnZS9wbmd8YUdNM0wyaGpZeTh4TkRrM016TTRNRFkxTnpFNE1nfDRmNTg5M2U5NGI1NzI1NjA0MmZkMzFmMDA0MDMzOTZiYTk1ZDA2NmRjZDRkOWQwNjhmNDcxNWQyNGM0M2I4MmU",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_5]: {
    calculation: () => 5 / 2,
    code: "1014",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_6]: {
    calculation: () => 6 / 2,
    code: "1016",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_7]: {
    calculation: () => 7 / 2,
    code: "1018",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_7_50]: {
    calculation: () => 7.5 / 2,
    code: "1204",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_8]: {
    calculation: () => 8 / 2,
    code: "1020",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_9]: {
    calculation: () => 9 / 2,
    code: "1022",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_10_95]: {
    calculation: () => 10.95 / 2,
    code: "4623",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_13]: {
    calculation: () => 13 / 2,
    code: "1237",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_18]: {
    calculation: () => 18 / 2,
    code: "1239",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_20]: {
    calculation: () => 20 / 2,
    code: "1034",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_29_99]: {
    calculation: () => 29.99 / 2,
    code: "1035",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_19_99]: {
    calculation: () => 19.99 / 2,
    code: "1196",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_22]: {
    calculation: () => 22 / 2,
    code: "1235",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_24]: {
    calculation: () => 24 / 2,
    code: "4626",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_25]: {
    calculation: () => 25 / 2,
    code: "1209",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_27]: {
    calculation: () => 27 / 2,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDU2OXxpbWFnZS9wbmd8YURsbEwyaGlPQzh4TlRZd01UWTJNREl6TVRjeE1BfGNlNmQ4OTc1MmYyYzVlZWM0YTE3YWUyOWI0MTllNjVmMWMyMzg4Y2E1Y2QxOWUzZDlhMGQ0ZmQ3MmQxZjgyZTM",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_28]: {
    calculation: () => 28 / 2,
    code: "1264",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_65]: {
    calculation: () => 65 / 2,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDczMnxpbWFnZS9wbmd8YURjNUwyZ3lPUzh6TVRBeE1EWTBNRGsxTXpNM05BfDkzOGIzMjA1YWMyNzMyMDNkOGFiZjI1ZTMwMmI4MDgxMWM3MDVlOWViODY4OGY0NTExMDFlZTVhOTE4YzFiOWE",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_75]: {
    calculation: () => 75 / 2,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDUzN3xpbWFnZS9wbmd8YURkakwyZzVaUzh6TXpNM05qUTNNRGs1TURnM09BfDNjMTVjYTRmYzVmYTgyMzhlMzU3ZDg3MTk4ZWRjMjJiM2EyZjI5OGM4ZThmNjg2MGY4MTQzMWJjMmUxZmJlM2M",
    purchaseAmount: 2,
  },
  // INCORRECT CODE
  // [KruidvatDealType.TWO_FOR_59_99]: {
  //   calculation: () => 59.99 / 2,
  //   code: "1034",
  //   purchaseAmount: 2,
  // },
  [KruidvatDealType.THREE_FOR_3]: {
    calculation: () => 1,
    code: "4603",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_3_DUPLICATE]: {
    calculation: () => 1,
    code: "1042",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_5]: {
    calculation: () => 5 / 3,
    code: "4160",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_6]: {
    calculation: () => 6 / 3,
    code: "1044",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_6_50]: {
    calculation: () => 6.5 / 3,
    code: "4267",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_9]: {
    calculation: () => 9 / 3,
    code: "1047",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_20]: {
    calculation: () => 20 / 3,
    code: "1294",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_53]: {
    calculation: () => 53 / 3,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDcyOHxpbWFnZS9wbmd8YURSa0wyaGlaUzh6TXpFek5EUXlOekEzT0RZNE5nfGJlZmU3NzRjNjBkMTBkZDBlY2Y2ZGIwMjMzYTRkOTMyZmI3ZTJjN2VjN2UxNDQ3MjBlZGUyOTIxYjgyNzZlMDY",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_99_99]: {
    calculation: () => 99.99 / 3,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDU5OXxpbWFnZS9wbmd8YUdGakwyZzFOeTh6TVRBeE1EWXlNekF5T1RJM09BfDBkNjA3MjdhMmVlYzE3MzQ4OTM1NjIxM2JiMTFhNTBlNmM2NTI5NmEzNzE5YjBlODE0OTRhNWY0MTQ4ZDcwYzI",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_10]: {
    calculation: () => 10 / 3,
    code: "1048",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_10_DUPLICATE]: {
    calculation: () => 10 / 3,
    code: "13515",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_11]: {
    calculation: () => 11 / 3,
    code: "4310",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_12]: {
    calculation: () => 12 / 3,
    code: "1226",
    purchaseAmount: 3,
  },
  [KruidvatDealType.TWO_FOR_10]: {
    calculation: () => 10 / 2,
    code: "1025",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_12]: {
    calculation: () => 12 / 2,
    code: "1028",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_11]: {
    calculation: () => 11 / 2,
    code: "1027",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_PLUS_ONE]: {
    calculation: (price: number) => (price + price) / 3,
    code: "1036",
    purchaseAmount: 3,
  },
  [KruidvatDealType.TWO_PLUS_TWO]: {
    calculation: (price: number) => price / 2,
    code: "1037",
    purchaseAmount: 4,
  },
  [KruidvatDealType.TWO_PLUS_THREE]: {
    calculation: (price: number) => (price + price) / 5,
    code: "1118",
    purchaseAmount: 5,
  },
  [KruidvatDealType.THREE_PLUS_TWO]: {
    calculation: (price: number) => (price * 3) / 5,
    code: "1050",
    purchaseAmount: 5,
  },
  [KruidvatDealType.FOUR_PLUS_ONE]: {
    calculation: (price: number) => (price * 4) / 5,
    code: "1125",
    purchaseAmount: 5,
  },
  [KruidvatDealType.SIX_PLUS_ONE]: {
    calculation: (price: number) => (price * 6) / 7,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDc0OXxpbWFnZS9wbmd8YURObUwyaGtNQzh6TXpZeU56WXlPVFV4T0RnM09BfDU1ZGRlZGQ2ODkyNDIwMmQyNTM4NzdkY2E3OTgwN2UyMzE3YTI1OTU0NDMyZDJjY2Y0MzEyNDA1ZjE0OTNkNzI",
    purchaseAmount: 7,
  },
  [KruidvatDealType.SECOND_FOR_ONE]: {
    calculation: (price: number) => (price + 1) / 2,
    code: "1038",
    purchaseAmount: 2,
  },
  [KruidvatDealType.SECOND_FOR_TWO]: {
    calculation: (price: number) => (price + 2) / 2,
    code: "1228",
    purchaseAmount: 2,
  },
  [KruidvatDealType.SECOND_HALF_PRICE]: {
    calculation: (price: number) => price * 0.75,
    code: "1039",
    purchaseAmount: 2,
  },
  [KruidvatDealType.SECOND_HALF_PRICE_DUPLICATE]: {
    calculation: (price: number) => price * 0.75,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDYzNHxpbWFnZS9wbmd8YURVeEwyZzRNUzh4TkRrME56UTNNalUzTWpRME5nfDBjOGI1YjYxMDBkMWE1YzIzMGFkMGY3OTQyODNiYjQ0N2YxYzJhMDI4ZWJmZGI2OWI1MzBhOWU1YTY3MjkyZGY",
    purchaseAmount: 2,
  },
  [KruidvatDealType.FOUR_FOR_5]: {
    calculation: () => 5 / 4,
    code: "1054",
    purchaseAmount: 4,
  },
  [KruidvatDealType.TEN_PERCENT_OFF]: {
    calculation: (price: number) => price - price * 0.1,
    code: "1058",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FIFTEEN_PERCENT_OFF]: {
    calculation: (price: number) => price - price * 0.15,
    code: "1059",
    purchaseAmount: 1,
  },
  [KruidvatDealType.TWENTY_PERCENT_OFF]: {
    calculation: (price: number) => price - price * 0.2,
    code: "1061",
    purchaseAmount: 1,
  },
  [KruidvatDealType.TWENTY_FIVE_PERCENT_OFF]: {
    calculation: (price: number) => price - price * 0.25,
    code: "1062",
    purchaseAmount: 1,
  },
  [KruidvatDealType.TWENTY_FIVE_PERCENT_EXTRA_OFF]: {
    calculation: (price: number) => price - price * 0.25,
    code: "1557",
    purchaseAmount: 1,
  },
  [KruidvatDealType.THIRTY_PERCENT_OFF]: {
    calculation: (price: number) => price - price * 0.3,
    code: "1064",
    purchaseAmount: 1,
  },
  [KruidvatDealType.THIRTY_THREE_PERCENT_OFF]: {
    calculation: (price: number) => price - price * 0.33,
    code: "1193",
    purchaseAmount: 1,
  },
  [KruidvatDealType.THIRTY_FIVE_PERCENT_OFF]: {
    calculation: (price: number) => price - price * 0.35,
    code: "1065",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOURTY_PERCENT_OFF]: {
    calculation: (price: number) => price - price * 0.4,
    code: "1067",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FIFTY_PERCENT_OFF]: {
    calculation: (price: number) => price * 0.5,
    code: "1068",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FIFTY_FIVE_PERCENT_OFF]: {
    calculation: (price: number) => price * 0.55,
    code: "1131",
    purchaseAmount: 1,
  },
  [KruidvatDealType.SIXTY_PERCENT_OFF]: {
    calculation: (price: number) => price - price * 0.6,
    code: "1133",
    purchaseAmount: 1,
  },
  [KruidvatDealType.SIXTY_ONE_PERCENT_OFF]: {
    calculation: (price: number) => price - price * 0.61,
    code: "4970",
    purchaseAmount: 1,
  },
  [KruidvatDealType.SEVENTY_FIVE_PERCENT_EXTRA_OFF]: {
    calculation: (price: number) => price - price * 0.75,
    code: "1450",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_1_EACH]: {
    calculation: () => 1,
    code: "1086",
    purchaseAmount: 1,
  },
  [KruidvatDealType.THREE_FOR_2]: {
    calculation: () => 2 / 3,
    code: "1167",
    purchaseAmount: 3,
  },
  [KruidvatDealType.FIVE_FOR_3]: {
    calculation: () => 3 / 5,
    code: "1159",
    purchaseAmount: 5,
  },
  [KruidvatDealType.FIVE_FOR_5]: {
    calculation: () => 1,
    code: "1176",
    purchaseAmount: 5,
  },
  [KruidvatDealType.FIVE_FOR_6]: {
    calculation: () => 6 / 5,
    code: "4110",
    purchaseAmount: 5,
  },
  [KruidvatDealType.FIVE_FOR_10]: {
    calculation: () => 2,
    code: "1145",
    purchaseAmount: 5,
  },
  [KruidvatDealType.SIX_FOR_7]: {
    calculation: () => 7 / 6,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDAzNHxpbWFnZS9wbmd8YURBNUwyaG1OUzh5TnpFek5EVTFPVGcwTmpRek1BfDkxNzRhZTFiOTU2ODg3M2IyY2M5OWFjODAxN2RhZTdjYTk0N2QxZjhkZmVlYzI1ZTBhOWQzNjY5Mjc1MWZhOGE",
    purchaseAmount: 6,
  },
  [KruidvatDealType.EIGHT_FOR_10]: {
    calculation: () => 10 / 8,
    code: "1572",
    purchaseAmount: 8,
  },
  [KruidvatDealType.NINE_FOR_9_99]: {
    calculation: () => 9.99 / 9,
    code: "4141",
    purchaseAmount: 9,
  },
  [KruidvatDealType.FOUR_FOR_10]: {
    calculation: () => 10 / 4,
    code: "1183",
    purchaseAmount: 4,
  },
  [KruidvatDealType.THREE_FOR_7]: {
    calculation: () => 7 / 3,
    code: "1191",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_7_50]: {
    calculation: () => 7.5 / 3,
    code: "1045",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_7_99]: {
    calculation: () => 7.99 / 3,
    code: "1146",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_13]: {
    calculation: () => 13 / 3,
    code: "4550",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_35]: {
    calculation: () => 35 / 3,
    code: "1563",
    purchaseAmount: 3,
  },
  [KruidvatDealType.FOUR_FOR_6]: {
    calculation: () => 6 / 4,
    code: "1189",
    purchaseAmount: 4,
  },
  [KruidvatDealType.FOUR_FOR_6_99]: {
    calculation: () => 6.99 / 4,
    code: "1262",
    purchaseAmount: 4,
  },
  [KruidvatDealType.FOUR_FOR_7]: {
    calculation: () => 7 / 4,
    code: "1382",
    purchaseAmount: 4,
  },
  [KruidvatDealType.FOUR_FOR_8]: {
    calculation: () => 8 / 4,
    code: "1403",
    purchaseAmount: 4,
  },
  [KruidvatDealType.FOUR_FOR_9]: {
    calculation: () => 9 / 4,
    code: "1402",
    purchaseAmount: 4,
  },
  [KruidvatDealType.FOUR_FOR_30]: {
    calculation: () => 30 / 4,
    code: "1578",
    purchaseAmount: 4,
  },
  [KruidvatDealType.FOUR_FOR_35]: {
    calculation: () => 35 / 4,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDc1MXxpbWFnZS9wbmd8YURGa0wyaG1aaTh6TXpVMU9EWTRORGcyTURRME5nfDMwMGY0ZjM5NGQ5OTdhZTk4N2RjM2M0ZTI5MWIzZmU1MzYxYzNlY2M5ZmZhZGMyMmNhNmRjMDYyOTRhOTAxYTc",
    purchaseAmount: 4,
  },
  [KruidvatDealType.TWO_FOR_9_95]: {
    calculation: () => 9.95 / 2,
    code: "1024",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_9_99]: {
    calculation: () => 9.99 / 2,
    code: "1153",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_14]: {
    calculation: () => 14 / 2,
    code: "1238",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_15]: {
    calculation: () => 15 / 2,
    code: "1156",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_16]: {
    calculation: () => 16 / 2,
    code: "1031",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_19]: {
    calculation: () => 19 / 2,
    code: "1033",
    purchaseAmount: 2,
  },
  [KruidvatDealType.ALL_FOR_1_50_EACH]: {
    calculation: () => 1.5,
    code: "1088",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_2_50_EACH]: {
    calculation: () => 2.5,
    code: "1415",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_2_99_EACH]: {
    calculation: () => 2.99,
    code: "1092",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_3_99_EACH]: {
    calculation: () => 3.99,
    code: "1412",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_7_99_EACH]: {
    calculation: () => 7.99,
    code: "1104",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_7_99_EACH_DUPLICATE]: {
    calculation: () => 7.99,
    code: "1080",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_2_EACH]: {
    calculation: () => 2,
    code: "1090",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_3_EACH]: {
    calculation: () => 3,
    code: "1093",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_4_EACH]: {
    calculation: () => 4,
    code: "1095",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_4_50_EACH]: {
    calculation: () => 4.5,
    code: "1324",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_4_99_EACH]: {
    calculation: () => 4.99,
    code: "1096",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_5_EACH]: {
    calculation: () => 5,
    code: "1097",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_6_EACH]: {
    calculation: () => 6,
    code: "1100",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_6_50_EACH]: {
    calculation: () => 6.5,
    code: "1366",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_7_EACH]: {
    calculation: () => 7,
    code: "1101",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_7_49_EACH]: {
    calculation: () => 7.49,
    code: "1102",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_7_50_EACH]: {
    calculation: () => 7.5,
    code: "1103",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_8_99_EACH]: {
    calculation: () => 8.99,
    code: "1407",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_9_EACH]: {
    calculation: () => 9,
    code: "1107",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_9_99_EACH]: {
    calculation: () => 9.99,
    code: "1109",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_10_EACH]: {
    calculation: () => 10,
    code: "1110",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_12_EACH]: {
    calculation: () => 12,
    code: "1180",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_12_50_EACH]: {
    calculation: () => 12.5,
    code: "1368",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_13_EACH]: {
    calculation: () => 13,
    code: "1399",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_14_99_EACH]: {
    calculation: () => 14.99,
    code: "1231",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_15_EACH]: {
    calculation: () => 15,
    code: "1112",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_16_99_EACH]: {
    calculation: () => 16.99,
    code: "1431",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_17_99_EACH]: {
    calculation: () => 17.99,
    code: "1493",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_18_99_EACH]: {
    calculation: () => 18.99,
    code: "1319",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_19_99_EACH]: {
    calculation: () => 19.99,
    code: "1150",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_20_EACH]: {
    calculation: () => 20,
    code: "1114",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_24_99_EACH]: {
    calculation: () => 24.99,
    code: "1490",
    purchaseAmount: 1,
  },
  [KruidvatDealType.THREE_FOR_8]: {
    calculation: () => 8 / 3,
    code: "1328",
    purchaseAmount: 3,
  },
  [KruidvatDealType.FIFTY_PERCENT_OFF_BY_5]: {
    calculation: (price: number) => price * 0.5,
    code: "5489",
    purchaseAmount: 5,
  },
  [KruidvatDealType.ALL_FOR_0_99_EACH]: {
    calculation: () => 0.99,
    code: "1085",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_1_29_EACH]: {
    calculation: () => 1.29,
    code: "1411",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_29_99_EACH]: {
    calculation: () => 29.99,
    code: "1115",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_34_99_EACH]: {
    calculation: () => 34.99,
    code: "1455",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_38_99_EACH]: {
    calculation: () => 38.99,
    code: "1507",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_39_99_EACH]: {
    calculation: () => 39.99,
    code: "1425",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_49_99_EACH]: {
    calculation: () => 49.99,
    code: "1453",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_5_PER_PACK]: {
    calculation: () => 5,
    code: "1175",
    purchaseAmount: 1,
  },
  [KruidvatDealType.TWO_OFF]: {
    calculation: (price: number) => price - 2,
    code: "1004",
    purchaseAmount: 1,
  },
  [KruidvatDealType.THREE_OFF]: {
    calculation: (price: number) => price - 3,
    code: "1040",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FIVE_OFF]: {
    calculation: (price: number) => price - 5,
    code: "1055",
    purchaseAmount: 1,
  },
  [KruidvatDealType.SIX_OFF]: {
    calculation: (price: number) => price - 6,
    code: "1187",
    purchaseAmount: 1,
  },
  [KruidvatDealType.NINE_OFF]: {
    calculation: (price: number) => price - 9,
    code: "1356",
    purchaseAmount: 1,
  },
  [KruidvatDealType.TEN_OFF]: {
    calculation: (price: number) => price - 10,
    code: "1057",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FIFTEEN_OFF]: {
    calculation: (price: number) => price - 15,
    code: "1251",
    purchaseAmount: 1,
  },
  [KruidvatDealType.TWENTY_OFF]: {
    calculation: (price: number) => price - 20,
    code: "1179",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_1_49]: {
    calculation: () => 1.49,
    code: "4169",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_3]: {
    calculation: () => 3,
    code: "4227",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_3_99]: {
    calculation: () => 3.99,
    code: "4149",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_4_39]: {
    calculation: () => 4.39,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDMzNHxpbWFnZS9wbmd8YURObEwyZzBZUzh6TXpnMU1EQTJOVFU0TkRFMU9BfDY3OWMzMDE5MWE0OTgyZDM2NTk2MjEzYWVkMjMwMjE3NGVlMzk2YzAxNWEwMWNlNzAzMWZmMmZhZTgzZjBkMWU",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_4_99]: {
    calculation: () => 4.99,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDE3N3xpbWFnZS9wbmd8YUdGbEwyZzJZaTh6TWpNM05qRXpNVGM0TURZek9BfDU0ODQxNDlhOWZhNjJmNjQyZmZjYTMyYmJlN2M4N2MzNGVhNTgwMDk3MmUxYTk3OWQwM2Q4ZGEyMzVhZTBiOTg",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_5]: {
    calculation: () => 5,
    code: "4190",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_5_49]: {
    calculation: () => 5.49,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDI5MnxpbWFnZS9wbmd8YURNMEwyZzRPQzh6TkRBMU1ERXpPVFUxTXpneU1nfDgyYzYyZTk5MDM4M2YwMDJhYmU5ZGM1OGZjMWI3MDljMTE2NTJiZGI5MGVhMDk4YzY4NmYxNjA3Mjg1MDE1MjM",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_5_75]: {
    calculation: () => 5.75,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDE1OXxpbWFnZS9wbmd8YURRekwyaGpPQzh6TkRFeU1qYzVNalUyTmpneE5BfDRhY2E1Mzg1MzJlNWQ5NDQ3MjIzNTI3OWU3NDQ5NjVmMTk0NDIzYjQyYjBmZjUwMmQ5MmYwNmIyNWZjM2EwYzE",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_5_99]: {
    calculation: () => 5.99,
    code: "4198",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_6]: {
    calculation: () => 6,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDE2OHxpbWFnZS9wbmd8YURjd0wyZzBZUzh6TWpFNE16UTRNamswTVRRM01BfGJjN2E4ZjI4OTZkZDQzNGVkZWI3NGUwYzEyMzc1MDViYWQzNGY1MzFmOTFkZjliZDAzNzE1NmZkM2QzZTcxNjc",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_7_99]: {
    calculation: () => 7.99,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDE2OHxpbWFnZS9wbmd8YURReUwyZ3pOQzh6TWpJME1qazJPVFEzTnpFMU1BfDM5NTRlYmExNTYyN2YwZmE5YjI0NTk0YTA2NDE5YTc0ZjViMDRkZDY5ZTk0MWY4NWFiYTdkMzc5ZmM0Yzc2YzE",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_8]: {
    calculation: () => 8,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDI0OXxpbWFnZS9wbmd8YUdOa0wyaGxPUzh6TWpRMk16UTFNall3TWpNNU9BfGIyNDBiODcwZjUzMWQyY2FmM2FlNmVkN2ZmMTg0ODI2YTcyOWVhOTJlYTEwMjdjZmM5ZjY5YjlhOTYwOTQ2YTQ",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_9]: {
    calculation: () => 9,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDIxNHxpbWFnZS9wbmd8YURoakwyZzRPQzh6TXpBMU56YzNNRGN6TXpVNU9BfDY4ODBmNzE5ODljMjQ0MzUwODgwZjc4YjgzNWVmYzIxNDQxMGZmYjAwZjM3YTNkYmQ5MjU4NWNiOTVhYmNlNzQ",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_9_99]: {
    calculation: () => 9.99,
    code: "4202",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_10]: {
    calculation: () => 10,
    code: "4494",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_11_99]: {
    calculation: () => 11.99,
    code: "4347",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_12_50]: {
    calculation: () => 12.5,
    code: "4610",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_13_95]: {
    calculation: () => 13.95,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDYyMXxpbWFnZS9wbmd8YURGbUwyaGxPUzh6TWpRMk16UTFNalkyTnprek5BfDg3NzJjOWJlODUxYWI2ZGJkMWY0YmIwY2Q1NjExZmJhZTBlNjkzZDAzNDgwMmRmNzQzNTk3NDMyN2YyM2UzN2E",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_14]: {
    calculation: () => 14,
    code: "4494",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_14_99]: {
    calculation: () => 14.99,
    code: "4499",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_15_99]: {
    calculation: () => 15.99,
    code: "4525",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_17_49]: {
    calculation: () => 17.49,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDQyOXxpbWFnZS9wbmd8YURReUwyZzVaUzh5TnpJME9UQXhORGd6TXpFNE1nfDA0MDhhZDc1YjAzOTgzMDQ2ZTkzMjVmNWQ1YWMxNGY0NWQyY2E1YTRlMmUyYjllYTgwN2M4MDI1NjQxMDkwNGI",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_24_99]: {
    calculation: () => 24.99,
    code: "4626",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_25]: {
    calculation: () => 25,
    code: "4628",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_26_50]: {
    calculation: () => 26.5,
    code: "4765",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_35]: {
    calculation: () => 35,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDY0NHxpbWFnZS9wbmd8YUdSbEwyZzROeTh6TXpBMU56YzNNRGM1T1RFek5BfGI0NzdlNzFlNzNjNjE3MzEzN2E2ZTY2YTcxNzg0ZTU2ZDcxNDc1YzEwZWIyMTM3OTIyYTM3Y2Y5OTVhMjcyOGM",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FPR_45_99]: {
    calculation: () => 45.99,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDQ1NXxpbWFnZS9wbmd8YURreEwyZ3pZeTh4TmpNeE1qazBNamc0TmprME1nfGNlMzI4ZGFiODM5NmMwN2NjY2ZiNzNiYzI3ZmM0YjU3OTVmOGQ3NDM2Zjk1ZWQ2ZGM1ZDg0NWJjNWZhYWZhNDQ",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_54_99]: {
    calculation: () => 54.99,
    code: "4432",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_59_99]: {
    calculation: () => 59.99,
    code: "4467",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_69_99]: {
    calculation: () => 69.99,
    code: "4590",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_89_99]: {
    calculation: () => 89.99,
    code: "4597",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_129_99]: {
    calculation: () => 129.99,
    code: "4496",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_249_99]: {
    calculation: () => 249.99,
    code: "4605",
    purchaseAmount: 1,
  },
});
