interface IDealInformation {
  calculation: (price: number) => number;
  code: string;
  purchaseAmount: number;
  requiresCard?: boolean;
}

export enum KruidvatDealType {
  // X + Y
  ONE_PLUS_ONE = 1,
  ONE_PLUS_ONE_DUPLICATE,
  ONE_PLUS_ONE_WITH_CARD,
  ONE_PLUS_TWO,
  ONE_PLUS_TWO_WITH_CARD,
  TWO_PLUS_ONE,
  TWO_PLUS_TWO,
  TWO_PLUS_TWO_WITH_CARD,
  TWO_PLUS_THREE,
  TWO_PLUS_FOUR_WITH_CARD,
  THREE_PLUS_ONE,
  THREE_PLUS_TWO,
  THREE_PLUS_THREE,
  FOUR_PLUS_ONE,
  SIX_PLUS_ONE,
  SIX_PLUS_FOUR,
  EIGHT_PLUS_TWO,
  EIGHT_PLUS_THREE,

  // 2 for €X
  TWO_FOR_1_50,
  TWO_FOR_2,
  TWO_FOR_2_49,
  TWO_FOR_2_50,
  TWO_FOR_3,
  TWO_FOR_3_WITH_CARD,
  TWO_FOR_4,
  TWO_FOR_4_49,
  TWO_FOR_4_50,
  TWO_FOR_4_69,
  TWO_FOR_4_99,
  TWO_FOR_5,
  TWO_FOR_6,
  TWO_FOR_7,
  TWO_FOR_7_50,
  TWO_FOR_8,
  TWO_FOR_9,
  TWO_FOR_9_50,
  TWO_FOR_9_95,
  TWO_FOR_9_99,
  TWO_FOR_10,
  TWO_FOR_10_95,
  TWO_FOR_11,
  TWO_FOR_12,
  TWO_FOR_13,
  TWO_FOR_13_99,
  TWO_FOR_14,
  TWO_FOR_14_99,
  TWO_FOR_15,
  TWO_FOR_16,
  TWO_FOR_16_99,
  TWO_FOR_18,
  TWO_FOR_19,
  TWO_FOR_19_99,
  TWO_FOR_20,
  TWO_FOR_22,
  TWO_FOR_24,
  TWO_FOR_25,
  TWO_FOR_27,
  TWO_FOR_27_50,
  TWO_FOR_28,
  TWO_FOR_29_50,
  TWO_FOR_29_99,
  TWO_FOR_30,
  TWO_FOR_55,
  TWO_FOR_65,
  TWO_FOR_75,
  // TWO_FOR_59_99,

  // 3 for €X
  THREE_FOR_2,
  THREE_FOR_3,
  THREE_FOR_3_DUPLICATE,
  THREE_FOR_4,
  THREE_FOR_5,
  THREE_FOR_6,
  THREE_FOR_6_50,
  THREE_FOR_7,
  THREE_FOR_7_49,
  THREE_FOR_7_50,
  THREE_FOR_7_99,
  THREE_FOR_8,
  THREE_FOR_9,
  THREE_FOR_9_99,
  THREE_FOR_10,
  THREE_FOR_10_DUPLICATE,
  THREE_FOR_11,
  THREE_FOR_12,
  THREE_FOR_13,
  THREE_FOR_15,
  THREE_FOR_20,
  THREE_FOR_22_50,
  THREE_FOR_24,
  THREE_FOR_25,
  THREE_FOR_29,
  THREE_FOR_30,
  THREE_FOR_35,
  THREE_FOR_37,
  THREE_FOR_38,
  THREE_FOR_39,
  THREE_FOR_40,
  THREE_FOR_42,
  THREE_FOR_53,
  THREE_FOR_64_99,
  THREE_FOR_99_99,

  // 4 for €X
  FOUR_FOR_5,
  FOUR_FOR_5_WITH_CARD,
  FOUR_FOR_6,
  FOUR_FOR_6_99,
  FOUR_FOR_7,
  FOUR_FOR_8,
  FOUR_FOR_9,
  FOUR_FOR_10,
  FOUR_FOR_30,
  FOUR_FOR_35,
  FOUR_FOR_48,
  FOUR_FOR_70,

  // 5 for €X
  FIVE_FOR_3,
  FIVE_FOR_5,
  FIVE_FOR_6,
  FIVE_FOR_10,
  FIVE_FOR_12,

  // 6 for €X
  SIX_FOR_5,
  SIX_FOR_6,
  SIX_FOR_7,
  SIX_FOR_10,

  // 7 for €X
  SEVEN_FOR_16_99,

  // 8 for €X
  EIGHT_FOR_10,
  EIGHT_FOR_16_99,

  // 9 for €X
  NINE_FOR_9_99,

  // 10 for €X
  TEN_FOR_10,

  // X% off
  TEN_PERCENT_OFF,
  TEN_PERCENT_OFF_WITH_CARD,
  FIFTEEN_PERCENT_OFF,
  TWENTY_PERCENT_OFF,
  TWENTY_PERCENT_OFF_WITH_CARD,
  TWENTY_FIVE_PERCENT_OFF,
  TWENTY_FIVE_PERCENT_OFF_WITH_CARD,
  TWENTY_FIVE_PERCENT_EXTRA_OFF,
  THIRTY_PERCENT_OFF,
  THIRTY_PERCENT_OFF_WITH_CARD,
  THIRTY_THREE_PERCENT_OFF,
  THIRTY_FIVE_PERCENT_OFF,
  FOURTY_PERCENT_OFF,
  FOURTY_PERCENT_OFF_WITH_CARD,
  FIFTY_PERCENT_OFF,
  FIFTY_PERCENT_OFF_WITH_CARD,
  FIFTY_FIVE_PERCENT_OFF,
  SIXTY_PERCENT_OFF,
  SIXTY_ONE_PERCENT_OFF,
  SEVENTY_FIVE_PERCENT_EXTRA_OFF,
  EIGHTY_PERCENT_OFF,

  // X% off by X amount
  FIFTY_PERCENT_OFF_BY_5,

  // All for €X each
  ALL_FOR_0_99_EACH,
  ALL_FOR_1_EACH,
  ALL_FOR_1_29_EACH,
  ALL_FOR_1_50_EACH,
  ALL_FOR_1_99_EACH,
  ALL_FOR_2_EACH,
  ALL_FOR_2_EACH_DUPLICATE,
  ALL_FOR_2_50_EACH,
  ALL_FOR_2_99_EACH,
  ALL_FOR_3_EACH,
  ALL_FOR_3_49_EACH,
  ALL_FOR_3_99_EACH,
  ALL_FOR_4_EACH,
  ALL_FOR_4_50_EACH,
  ALL_FOR_4_99_EACH,
  ALL_FOR_4_99_EACH_DUPLICATE,
  ALL_FOR_5_EACH,
  ALL_FOR_6_EACH,
  ALL_FOR_6_50_EACH,
  ALL_FOR_7_EACH,
  ALL_FOR_7_EACH_DUPLICATE,
  ALL_FOR_7_49_EACH,
  ALL_FOR_7_50_EACH,
  ALL_FOR_7_99_EACH,
  ALL_FOR_7_99_EACH_DUPLICATE,
  ALL_FOR_8_EACH,
  ALL_FOR_8_99_EACH,
  ALL_FOR_9_EACH,
  ALL_FOR_9_49_EACH,
  ALL_FOR_9_99_EACH,
  ALL_FOR_10_EACH,
  ALL_FOR_11_99_EACH,
  ALL_FOR_12_EACH,
  ALL_FOR_12_50_EACH,
  ALL_FOR_12_99_EACH,
  ALL_FOR_13_EACH,
  ALL_FOR_13_99_EACH,
  ALL_FOR_14_99_EACH,
  ALL_FOR_15_EACH,
  ALL_FOR_16_99_EACH,
  ALL_FOR_17_99_EACH,
  ALL_FOR_18_99_EACH,
  ALL_FOR_19_99_EACH,
  ALL_FOR_20_EACH,
  ALL_FOR_24_99_EACH,
  ALL_FOR_26_99_EACH,
  ALL_FOR_29_99_EACH,
  ALL_FOR_34_99_EACH,
  ALL_FOR_36_99_EACH,
  ALL_FOR_38_99_EACH,
  ALL_FOR_39_99_EACH,
  ALL_FOR_49_99_EACH,
  ALL_FOR_99_99_EACH,

  // All for €X per pack
  ALL_FOR_5_PER_PACK,

  // Second for ...
  SECOND_FOR_ONE,
  SECOND_FOR_TWO,
  SECOND_HALF_PRICE,
  SECOND_FOR_60_PERCENT_OFF,
  SECOND_HALF_PRICE_DUPLICATE,
  SECOND_HALF_PRICE_WITH_CARD,

  // €X off
  ONE_OFF,
  TWO_OFF,
  THREE_OFF,
  FOUR_OFF,
  FIVE_OFF,
  SIX_OFF,
  EIGHT_OFF,
  NINE_OFF,
  TEN_OFF,
  FIFTEEN_OFF,
  TWENTY_OFF,

  // For X
  FOR_0_89_WITH_CARD,
  FOR_0_99,
  FOR_1_49,
  FOR_1_50_WITH_CARD,
  FOR_1_99_WITH_CARD,
  FOR_2_75,
  FOR_2_99,
  FOR_3,
  FOR_3_WITH_CARD,
  FOR_3_99,
  FOR_4,
  FOR_4_39,
  FOR_4_99,
  FOR_4_99_WITH_CARD,
  FOR_5,
  FOR_5_49,
  FOR_5_75,
  FOR_5_99,
  FOR_6,
  FOR_6_49,
  FOR_6_99,
  FOR_7_50,
  FOR_7_99,
  FOR_8,
  FOR_9,
  FOR_9_99,
  FOR_9_99_WITH_CARD,
  FOR_10,
  FOR_10_WITH_CARD,
  FOR_10_49,
  FOR_11_99,
  FOR_12,
  FOR_12_50,
  FOR_13,
  FOR_13_95,
  FOR_14,
  FOR_14_99,
  FOR_14_99_WITH_CARD,
  FOR_15,
  FOR_15_99,
  FOR_17,
  FOR_17_49,
  FOR_17_99,
  FOR_19_99,
  FOR_19_99_WITH_CARD,
  FOR_24_50,
  FOR_24_99,
  FOR_24_99_WITH_CARD,
  FOR_25,
  FOR_26_50,
  FOR_29_99,
  FOR_32_99,
  FOR_33_99,
  FOR_35,
  FPR_44_99,
  FPR_45,
  FPR_45_99,
  FOR_47_99,
  FOR_54_99,
  FOR_59_99,
  FOR_69_99,
  FOR_87_49,
  FOR_89_99,
  // FOR_109,
  FOR_129_99,
  FOR_249_99,

  // Stapelkorting
  STACK_25_PERCENT_AT_3,
  STACK_40_PERCENT_AT_3,
  STACK_60_PERCENT_AT_3,
  STACK_15_PERCENT_AT_4,
}

export const kruidvatDealInformation: Record<
  KruidvatDealType,
  IDealInformation
> = Object.freeze({
  [KruidvatDealType.ONE_PLUS_ONE]: {
    calculation: (price: number) => price / 2,
    code: "1003",
    purchaseAmount: 2,
  },
  [KruidvatDealType.ONE_PLUS_ONE_DUPLICATE]: {
    calculation: (price: number) => price / 2,
    code: "5261",
    purchaseAmount: 2,
  },
  [KruidvatDealType.ONE_PLUS_ONE_WITH_CARD]: {
    calculation: (price: number) => price / 2,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8Mzk1MHxpbWFnZS9wbmd8YUdOaUwyaG1NUzh6TXpneE1qTTFOREF6T1Rnek9BfDc4ZjQ4MGIxNmViN2Q5NWRjMWZmZTcyZDYzZmUwOGFlOWY3NzgzZDk1MDIxN2U5NzZjMGYwMmE3ZmUwYTExYWI",
    purchaseAmount: 2,
    requiresCard: true,
  },
  [KruidvatDealType.ONE_PLUS_TWO]: {
    calculation: (price: number) => price / 3,
    code: "1467",
    purchaseAmount: 3,
  },
  [KruidvatDealType.ONE_PLUS_TWO_WITH_CARD]: {
    calculation: (price: number) => price / 3,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDI5N3xpbWFnZS9wbmd8YUdaaEwyaGxZUzh6TXpneE1qTTFOREl6TmpRME5nfGY5ZWMzMzk5NzJlODIyNTgyNGQ5NzQwMzkzNWMyNzY3NDc1ZDRjNTdiYTVkMTU3NmNlY2JiNjUzNzI3MDNmMzE",
    purchaseAmount: 3,
    requiresCard: true,
  },
  [KruidvatDealType.TWO_PLUS_ONE]: {
    calculation: (price: number) => (price + price) / 3,
    code: "1036",
    purchaseAmount: 3,
  },
  [KruidvatDealType.TWO_PLUS_TWO]: {
    calculation: (price: number) => price / 2,
    code: "1037",
    purchaseAmount: 4,
  },
  [KruidvatDealType.TWO_PLUS_TWO_WITH_CARD]: {
    calculation: (price: number) => price / 2,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDI2OHxpbWFnZS9wbmd8YUdVNUwyaGxOeTh6TXpneE1qTTFORE13TVRrNE1nfGE1MTdiMGIyN2I1YTEwZWNhMjk0ODljNmYzNzgyMjE2NWViNzUwOWMzNGFkNmY0MGVlN2FmYzg5ODBjM2MxZjQ",
    purchaseAmount: 4,
    requiresCard: true,
  },
  [KruidvatDealType.TWO_PLUS_THREE]: {
    calculation: (price: number) => (price + price) / 5,
    code: "1118",
    purchaseAmount: 5,
  },
  [KruidvatDealType.TWO_PLUS_FOUR_WITH_CARD]: {
    calculation: (price: number) => (price + price) / 6,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8Mzc4MnxpbWFnZS9wbmd8YUdJeEwyaGlaaTh6TkRVd05UUXlNalF6T0RRek1BfDBiN2UzMWRiYjk3MTBjOGNiODMzMjAwNDdiZDNlNDJhYzQ5OGM0OThlNDVjNjBlMTQzOTc2OGFlOWNjYjlmNDg",
    purchaseAmount: 6,
    requiresCard: true,
  },
  [KruidvatDealType.THREE_PLUS_ONE]: {
    calculation: (price: number) => (price * 3) / 4,
    code: "1122",
    purchaseAmount: 4,
  },
  [KruidvatDealType.THREE_PLUS_TWO]: {
    calculation: (price: number) => (price * 3) / 5,
    code: "1050",
    purchaseAmount: 5,
  },
  [KruidvatDealType.THREE_PLUS_THREE]: {
    calculation: (price: number) => (price * 3) / 6,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDUxN3xpbWFnZS9wbmd8YUdaaEwyaGlPUzh4TWpZM09UQTJORFE0TlRreE9BfDA2OGUxOGU5MDgyZjFhMzhkMGQyOGM2MGQ5YzIwNzllMTE3M2JlZjFhZDE4YzkwNmE0ZGFiOTYxMWU5NWQzOTQ",
    purchaseAmount: 6,
    requiresCard: true,
  },
  [KruidvatDealType.FOUR_PLUS_ONE]: {
    calculation: (price: number) => (price * 4) / 5,
    code: "1125",
    purchaseAmount: 5,
  },
  [KruidvatDealType.SIX_PLUS_ONE]: {
    calculation: (price: number) => (price * 6) / 7,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDc0OXxpbWFnZS9wbmd8YURObUwyaGtNQzh6TXpZeU56WXlPVFV4T0RnM09BfDU1ZGRlZGQ2ODkyNDIwMmQyNTM4NzdkY2E3OTgwN2UyMzE3YTI1OTU0NDMyZDJjY2Y0MzEyNDA1ZjE0OTNkNzI",
    purchaseAmount: 7,
  },
  [KruidvatDealType.SIX_PLUS_FOUR]: {
    calculation: (price: number) => (price * 6) / 10,
    code: "1621",
    purchaseAmount: 10,
  },
  [KruidvatDealType.EIGHT_PLUS_TWO]: {
    calculation: (price: number) => (price * 8) / 10,
    code: "1056",
    purchaseAmount: 10,
  },
  [KruidvatDealType.EIGHT_PLUS_THREE]: {
    calculation: (price: number) => (price * 8) / 11,
    code: "1642",
    purchaseAmount: 11,
  },
  [KruidvatDealType.TWO_FOR_1_50]: {
    calculation: () => 1.5 / 2,
    code: "1005",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_2]: {
    calculation: () => 2.5 / 2,
    code: "1007",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_2_49]: {
    calculation: () => 2.49 / 2,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDMzMnxpbWFnZS9wbmd8YUdKakwyZzRNUzh6TXpBMU56YzNNRGt6TURJd05nfGYxNGYyZGMyNjUwZDUxZmE4OTU4ZGYxZjk1ZTJhMzdjMjI5OTUyMjA2MTgzYjg5NmIwNmFhMTQwNjQ3OWIyYjc",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_2_50]: {
    calculation: () => 1,
    code: "1008",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_3]: {
    calculation: () => 3 / 2,
    code: "1010",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_3_WITH_CARD]: {
    calculation: () => 3 / 2,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDEwOHxpbWFnZS9wbmd8YURFMEwyZzNNeTh6TXpneE1qTTFOVFkzT0RJek9BfGUwMGVhNjU1NGYwOWY2MTlkNjZhNjM2MjE4YTZmMmZhNmFhY2JjNTBmNDRmZmI4MzYxMWE0YmYxZTIyMDc1Mzc",
    purchaseAmount: 2,
    requiresCard: true,
  },
  [KruidvatDealType.TWO_FOR_4]: {
    calculation: () => 4 / 2,
    code: "1013",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_4_49]: {
    calculation: () => 4.49 / 2,
    code: "1202",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_4_50]: {
    calculation: () => 4.5 / 2,
    code: "4291",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_4_69]: {
    calculation: () => 4.69 / 2,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDI4NXxpbWFnZS9wbmd8YUdNM0wyaGpZeTh4TkRrM016TTRNRFkxTnpFNE1nfDRmNTg5M2U5NGI1NzI1NjA0MmZkMzFmMDA0MDMzOTZiYTk1ZDA2NmRjZDRkOWQwNjhmNDcxNWQyNGM0M2I4MmU",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_4_99]: {
    calculation: () => 4.99 / 2,
    code: "1222",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_5]: {
    calculation: () => 5 / 2,
    code: "1014",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_6]: {
    calculation: () => 6 / 2,
    code: "1016",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_7]: {
    calculation: () => 7 / 2,
    code: "1018",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_7_50]: {
    calculation: () => 7.5 / 2,
    code: "1204",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_8]: {
    calculation: () => 8 / 2,
    code: "1020",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_9]: {
    calculation: () => 9 / 2,
    code: "1022",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_9_50]: {
    calculation: () => 9.5 / 2,
    code: "1023",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_9_95]: {
    calculation: () => 9.95 / 2,
    code: "1024",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_9_99]: {
    calculation: () => 9.99 / 2,
    code: "1153",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_10]: {
    calculation: () => 10 / 2,
    code: "1025",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_10_95]: {
    calculation: () => 10.95 / 2,
    code: "4623",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_11]: {
    calculation: () => 11 / 2,
    code: "1027",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_12]: {
    calculation: () => 12 / 2,
    code: "1028",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_13]: {
    calculation: () => 13 / 2,
    code: "1237",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_13_99]: {
    calculation: () => 13.99 / 2,
    code: "1030",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_14]: {
    calculation: () => 14 / 2,
    code: "1238",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_14_99]: {
    calculation: () => 14.99 / 2,
    code: "1220",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_15]: {
    calculation: () => 15 / 2,
    code: "1156",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_16]: {
    calculation: () => 16 / 2,
    code: "1031",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_16_99]: {
    calculation: () => 16.99 / 2,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDY1MHxpbWFnZS9wbmd8YURJeUwyZ3lZeTh5T0RBNU9ESXdPVGMwTWpnM09BfDFlNDdjZjg1NmExOGM3YTY0MGUwYWQ2ODkxMzI2MWNmZTcyMzAxOTJjZTEzNmVhNjlhYzg0NWMxNDQyM2EzMGU",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_18]: {
    calculation: () => 18 / 2,
    code: "1239",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_19]: {
    calculation: () => 19 / 2,
    code: "1033",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_19_99]: {
    calculation: () => 19.99 / 2,
    code: "1196",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_20]: {
    calculation: () => 20 / 2,
    code: "1034",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_22]: {
    calculation: () => 22 / 2,
    code: "1235",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_24]: {
    calculation: () => 24 / 2,
    code: "4626",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_25]: {
    calculation: () => 25 / 2,
    code: "1209",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_27]: {
    calculation: () => 27 / 2,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDU2OXxpbWFnZS9wbmd8YURsbEwyaGlPQzh4TlRZd01UWTJNREl6TVRjeE1BfGNlNmQ4OTc1MmYyYzVlZWM0YTE3YWUyOWI0MTllNjVmMWMyMzg4Y2E1Y2QxOWUzZDlhMGQ0ZmQ3MmQxZjgyZTM",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_27_50]: {
    calculation: () => 27.5 / 2,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDU1OHxpbWFnZS9wbmd8YUdJeUwyZzVNeTh5TnpJME9UQXhORFV3TlRVd01nfDE2NDZjMDc0ZmM1OTU1NDNiYjQ2MjY1NDMzMjJlZDNjY2EwNTg4ODc3NTRkMzFiOWYyMTc1MGY5MjBkMjQ4NmI",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_28]: {
    calculation: () => 28 / 2,
    code: "1264",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_29_50]: {
    calculation: () => 29.5 / 2,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDg0MnxpbWFnZS9wbmd8YURVMEwyaGpZaTh6TkRFeU1qYzVNall6TWpNMU1BfDRlMDNiNjNlM2Y3YmRkNTFlMDhhNjVjNDhhNWY3ZTEzYmVjMDlhMTUyMGVhMjViZjZiMmI2ZGQ4ZjQyMmUwZTQ",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_29_99]: {
    calculation: () => 29.99 / 2,
    code: "1035",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_30]: {
    calculation: () => 30 / 2,
    code: "1269",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_55]: {
    calculation: () => 55 / 2,
    code: "1409",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_65]: {
    calculation: () => 65 / 2,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDczMnxpbWFnZS9wbmd8YURjNUwyZ3lPUzh6TVRBeE1EWTBNRGsxTXpNM05BfDkzOGIzMjA1YWMyNzMyMDNkOGFiZjI1ZTMwMmI4MDgxMWM3MDVlOWViODY4OGY0NTExMDFlZTVhOTE4YzFiOWE",
    purchaseAmount: 2,
  },
  [KruidvatDealType.TWO_FOR_75]: {
    calculation: () => 75 / 2,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDUzN3xpbWFnZS9wbmd8YURkakwyZzVaUzh6TXpNM05qUTNNRGs1TURnM09BfDNjMTVjYTRmYzVmYTgyMzhlMzU3ZDg3MTk4ZWRjMjJiM2EyZjI5OGM4ZThmNjg2MGY4MTQzMWJjMmUxZmJlM2M",
    purchaseAmount: 2,
  },
  // INCORRECT CODE
  // [KruidvatDealType.TWO_FOR_59_99]: {
  //   calculation: () => 59.99 / 2,
  //   code: "1034",
  //   purchaseAmount: 2,
  // },
  [KruidvatDealType.THREE_FOR_2]: {
    calculation: () => 2 / 3,
    code: "1167",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_3]: {
    calculation: () => 1,
    code: "4603",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_3_DUPLICATE]: {
    calculation: () => 1,
    code: "1042",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_4]: {
    calculation: () => 4 / 3,
    code: "1158",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_5]: {
    calculation: () => 5 / 3,
    code: "4160",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_6]: {
    calculation: () => 6 / 3,
    code: "1044",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_6_50]: {
    calculation: () => 6.5 / 3,
    code: "4267",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_7]: {
    calculation: () => 7 / 3,
    code: "1191",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_7_49]: {
    calculation: () => 7.49 / 3,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDE5NnxpbWFnZS9wbmd8YUdaa0wyaGhaaTh5T0RFM01qZzNPVE16TVRNMU9BfDBmYTgyOThjNjgzMjA5OTE5NmFhN2Q5MzQ5MWMwOTMzOWMyMTc1MGZiNWY2NmRlMjNjNTMzNjM0ZDdiNTdhYjQ",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_7_50]: {
    calculation: () => 7.5 / 3,
    code: "1045",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_7_99]: {
    calculation: () => 7.99 / 3,
    code: "1146",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_8]: {
    calculation: () => 8 / 3,
    code: "1328",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_9]: {
    calculation: () => 9 / 3,
    code: "1047",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_9_99]: {
    calculation: () => 9.99 / 3,
    code: "1217",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_10]: {
    calculation: () => 10 / 3,
    code: "1048",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_10_DUPLICATE]: {
    calculation: () => 10 / 3,
    code: "13515",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_11]: {
    calculation: () => 11 / 3,
    code: "4310",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_12]: {
    calculation: () => 12 / 3,
    code: "1226",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_13]: {
    calculation: () => 13 / 3,
    code: "4550",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_15]: {
    calculation: () => 15 / 3,
    code: "1173",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_20]: {
    calculation: () => 20 / 3,
    code: "1294",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_22_50]: {
    calculation: () => 22.5 / 3,
    code: "1216",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_24]: {
    calculation: () => 24 / 3,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDU1M3xpbWFnZS9wbmd8YURjd0wyaGtOUzh4TVRRNE1UQTRORFkxTnpZNU5BfDQ0NGUyOGRiMTNkNjZiMzMwYzY3YWQ2ZmYxOGU1YmRlYjA3NTUzNDBkYWQwNzFkNzUwMjliYWFhZTE3OTIyMGU",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_25]: {
    calculation: () => 25 / 3,
    code: "1166",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_29]: {
    calculation: () => 29 / 3,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDYzMHxpbWFnZS9wbmd8YURGaEwyaG1PQzh5TnpFek5EVTFPVGt4TVRrMk5nfDcxZTMwMWYwMDY5YjI2ZWQ1NmJmZGRkNzAxYmYzZTdkMDJlYjVjNzliMzFkNmY3M2Q4YWZmYzM0M2ZiYWNhZTE",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_30]: {
    calculation: () => 30 / 3,
    code: "1236",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_35]: {
    calculation: () => 35 / 3,
    code: "1563",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_37]: {
    calculation: () => 37 / 3,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDQ5MXxpbWFnZS9wbmd8YURRNUwyaGtZUzh4TXpVMU1EVXdOVEF3TURrNU1BfGU1ZGI4Y2Y3NzUwMDI1ZDFkZDE0N2Y5MTJjNTMxMDAyM2U2NWQ0MGFmOTIzNDAwNDkzODIxOGE1ZTVlODUxNmY",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_38]: {
    calculation: () => 38 / 3,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDcyN3xpbWFnZS9wbmd8YURSakwyaGlPUzh4TlRZd01UWTJNREk1TnpJME5nfDcxNjhiOGMyNDY5ZjJkMWNlOGVhMGRiZjYzYTNhZmY5YTgxNTMxZmE1YzhiYTE4ZDFiYmViOGVkYTc2MjE2MzE",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_39]: {
    calculation: () => 39 / 3,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDY4MHxpbWFnZS9wbmd8YURSbUwyZ3dNaTh4TmprMk16WXpNalk1TXpJM09BfDE5MWI3YTg1NDJmY2VkYTg5ZmVhYjRmOWNhNTMyZmJkMGU3NTVmMjM0YTk5ODM5NDMyODMxZTJmMmRlOTM0NDI",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_40]: {
    calculation: () => 40 / 3,
    code: "4625",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_42]: {
    calculation: () => 42 / 3,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDU3OHxpbWFnZS9wbmd8YUdJM0wyaGxNQzh4TmpFNU1URXhNREExTXpreE9BfDViNDNhYzQ1ZDU4MTk5Zjg2OTFhY2VmMjdlN2Q5Njg2YjlmNDA2MDI3ODAwODU2ZTQ5MDIyMmNjMGE4MzBhZDg",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_53]: {
    calculation: () => 53 / 3,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDcyOHxpbWFnZS9wbmd8YURSa0wyaGlaUzh6TXpFek5EUXlOekEzT0RZNE5nfGJlZmU3NzRjNjBkMTBkZDBlY2Y2ZGIwMjMzYTRkOTMyZmI3ZTJjN2VjN2UxNDQ3MjBlZGUyOTIxYjgyNzZlMDY",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_64_99]: {
    calculation: () => 64.99 / 3,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDgxNXxpbWFnZS9wbmd8YURrM0wyZzVPQzh6TkRJNE16VTJPREV6TmpJeU1nfDc1NjkxOTFkZTEyYWRiYTc5YzY2NGE5Y2E4YjFiOGE0NGQyM2NhM2VjNWJiZjkyMjVlMDIyMGFjYzFlYmVmYjg",
    purchaseAmount: 3,
  },
  [KruidvatDealType.THREE_FOR_99_99]: {
    calculation: () => 99.99 / 3,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDU5OXxpbWFnZS9wbmd8YUdGakwyZzFOeTh6TVRBeE1EWXlNekF5T1RJM09BfDBkNjA3MjdhMmVlYzE3MzQ4OTM1NjIxM2JiMTFhNTBlNmM2NTI5NmEzNzE5YjBlODE0OTRhNWY0MTQ4ZDcwYzI",
    purchaseAmount: 3,
  },
  [KruidvatDealType.FOUR_FOR_5]: {
    calculation: () => 5 / 4,
    code: "1054",
    purchaseAmount: 4,
  },
  [KruidvatDealType.FOUR_FOR_5_WITH_CARD]: {
    calculation: () => 5 / 4,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDEzMHxpbWFnZS9wbmd8YURNekwyZzJPUzh6TXpneE1qTTFOVGswTURNNE1nfGJhOGIwMjNiNjcxYWY0MGMzMDVhZWZlYTZjM2QxZmJmYjg3NzE3MGM4NGJiNDBmYWRjYzk4YmZlMzE4ZGMyYWM",
    purchaseAmount: 4,
    requiresCard: true,
  },
  [KruidvatDealType.FOUR_FOR_6]: {
    calculation: () => 6 / 4,
    code: "1189",
    purchaseAmount: 4,
  },
  [KruidvatDealType.FOUR_FOR_6_99]: {
    calculation: () => 6.99 / 4,
    code: "1262",
    purchaseAmount: 4,
  },
  [KruidvatDealType.FOUR_FOR_7]: {
    calculation: () => 7 / 4,
    code: "1382",
    purchaseAmount: 4,
  },
  [KruidvatDealType.FOUR_FOR_8]: {
    calculation: () => 8 / 4,
    code: "1403",
    purchaseAmount: 4,
  },
  [KruidvatDealType.FOUR_FOR_9]: {
    calculation: () => 9 / 4,
    code: "1402",
    purchaseAmount: 4,
  },
  [KruidvatDealType.FOUR_FOR_10]: {
    calculation: () => 10 / 4,
    code: "1183",
    purchaseAmount: 4,
  },
  [KruidvatDealType.FOUR_FOR_30]: {
    calculation: () => 30 / 4,
    code: "1578",
    purchaseAmount: 4,
  },
  [KruidvatDealType.FOUR_FOR_35]: {
    calculation: () => 35 / 4,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDc1MXxpbWFnZS9wbmd8YURGa0wyaG1aaTh6TXpVMU9EWTRORGcyTURRME5nfDMwMGY0ZjM5NGQ5OTdhZTk4N2RjM2M0ZTI5MWIzZmU1MzYxYzNlY2M5ZmZhZGMyMmNhNmRjMDYyOTRhOTAxYTc",
    purchaseAmount: 4,
  },
  [KruidvatDealType.FOUR_FOR_48]: {
    calculation: () => 48 / 4,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDY5N3xpbWFnZS9wbmd8YURVeEwyaGxZUzh4TURreU5UWTVOelU1TnpRM01BfGQ2NTNmZDY0NmE4NTA2YzYzNTMyZWE5NDBlNDA3NTZmZmJlMmI0YzM2ZThlZGQyZWE2ZDI0YWY5YjUwY2MwMmU",
    purchaseAmount: 4,
  },
  [KruidvatDealType.FOUR_FOR_70]: {
    calculation: () => 70 / 4,
    code: "1638",
    purchaseAmount: 4,
  },
  [KruidvatDealType.FIVE_FOR_3]: {
    calculation: () => 3 / 5,
    code: "1159",
    purchaseAmount: 5,
  },
  [KruidvatDealType.FIVE_FOR_5]: {
    calculation: () => 1,
    code: "1176",
    purchaseAmount: 5,
  },
  [KruidvatDealType.FIVE_FOR_6]: {
    calculation: () => 6 / 5,
    code: "4110",
    purchaseAmount: 5,
  },
  [KruidvatDealType.FIVE_FOR_10]: {
    calculation: () => 2,
    code: "1145",
    purchaseAmount: 5,
  },
  [KruidvatDealType.FIVE_FOR_12]: {
    calculation: () => 12 / 5,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDQ4MnxpbWFnZS9wbmd8YURBeUwyZ3paaTh6TURJM05UWTBNamcxTVRNMU9BfGExYWFhZGNlNGY3MTZlZDM5OTRlNGVlYmE5YjljNmUyNmUxMzJjMTEzYWRkMzdlZWQyMTMzYjA2YWM2ZmU0ODM",
    purchaseAmount: 5,
  },
  [KruidvatDealType.SIX_FOR_5]: {
    calculation: () => 5 / 6,
    code: "1144",
    purchaseAmount: 6,
  },
  [KruidvatDealType.SIX_FOR_6]: {
    calculation: () => 1,
    code: "1566",
    purchaseAmount: 6,
  },
  [KruidvatDealType.SIX_FOR_7]: {
    calculation: () => 7 / 6,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDAzNHxpbWFnZS9wbmd8YURBNUwyaG1OUzh5TnpFek5EVTFPVGcwTmpRek1BfDkxNzRhZTFiOTU2ODg3M2IyY2M5OWFjODAxN2RhZTdjYTk0N2QxZjhkZmVlYzI1ZTBhOWQzNjY5Mjc1MWZhOGE",
    purchaseAmount: 6,
  },
  [KruidvatDealType.SIX_FOR_10]: {
    calculation: () => 10 / 6,
    code: "1571",
    purchaseAmount: 6,
  },
  [KruidvatDealType.SEVEN_FOR_16_99]: {
    calculation: () => 16.99 / 7,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDY0NnxpbWFnZS9wbmd8YUdFMkwyZ3lNaTh6TURVNE9ETXpOalF6T1RNeU5nfGI2MTAzNmNlMTIzY2I4NGViM2Q2ZjYxNDVhNDdhZGRiYzViYzI1MzU2OTM5ODY5ODdmODM0ZGRhYjZhOTkzZmI",
    purchaseAmount: 7,
  },
  [KruidvatDealType.EIGHT_FOR_10]: {
    calculation: () => 10 / 8,
    code: "1572",
    purchaseAmount: 8,
  },
  [KruidvatDealType.EIGHT_FOR_16_99]: {
    calculation: () => 16.99 / 8,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDY5MnxpbWFnZS9wbmd8YUdJM0wyZ3lOUzh6TURVNE9ETXpOalV3TkRnMk1nfGZmYjEyNzFiOTU0MjlkZTdhZjliOWE1ZDliZTFmM2E2MmE5ZjE5MTMxNWMyYjk0ZTc2YWUxMmQ3MWZmYjU0MWU",
    purchaseAmount: 8,
  },
  [KruidvatDealType.NINE_FOR_9_99]: {
    calculation: () => 9.99 / 9,
    code: "4141",
    purchaseAmount: 9,
  },
  [KruidvatDealType.TEN_FOR_10]: {
    calculation: () => 1,
    code: "1472",
    purchaseAmount: 10,
  },
  [KruidvatDealType.TEN_PERCENT_OFF]: {
    calculation: (price: number) => price - price * 0.1,
    code: "1058",
    purchaseAmount: 1,
  },
  [KruidvatDealType.TEN_PERCENT_OFF_WITH_CARD]: {
    calculation: (price: number) => price - price * 0.1,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDc2OHxpbWFnZS9wbmd8YUROaUwyaGxOeTh6TXpneE1qTTFORE0yTnpVeE9BfGI2YmRmMzVhZmQ2Y2MwNGQzZGFlODEwM2JjNjgyYTAyYTc2NTUwMjFmNTU0ODdlZjJhMTE4NjczYTVlMDg5YTc",
    purchaseAmount: 1,
    requiresCard: true,
  },
  [KruidvatDealType.FIFTEEN_PERCENT_OFF]: {
    calculation: (price: number) => price - price * 0.15,
    code: "1059",
    purchaseAmount: 1,
  },
  [KruidvatDealType.TWENTY_PERCENT_OFF]: {
    calculation: (price: number) => price - price * 0.2,
    code: "1061",
    purchaseAmount: 1,
  },
  [KruidvatDealType.TWENTY_PERCENT_OFF_WITH_CARD]: {
    calculation: (price: number) => price - price * 0.2,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDkxM3xpbWFnZS9wbmd8YURKaEwyaGxOQzh6TXpneE1qTTFORFF6TXpBMU5BfDBhMjlmZDE4MTcyMTZhNTBkYjU3NWJlYTJjMGQ0NDI3NWY2OGJkNTUxYWY5OTlkOWQzNWZmYTM4MDJlMzcxNjM",
    purchaseAmount: 1,
    requiresCard: true,
  },
  [KruidvatDealType.TWENTY_FIVE_PERCENT_OFF]: {
    calculation: (price: number) => price - price * 0.25,
    code: "1062",
    purchaseAmount: 1,
  },
  [KruidvatDealType.TWENTY_FIVE_PERCENT_OFF_WITH_CARD]: {
    calculation: (price: number) => price - price * 0.25,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDcxN3xpbWFnZS9wbmd8YURkakwyaGxNeTh6TXpneE1qTTFORFE1T0RVNU1BfDk3NTZhMmJkYmNiMTcxZGViNjRiOWQ3OWY0MDIyZDU1ZjExNDRjMTYwYjk5MGEzZWU1ZTExYmJhYzQxYzdkMmU",
    purchaseAmount: 1,
    requiresCard: true,
  },
  [KruidvatDealType.TWENTY_FIVE_PERCENT_EXTRA_OFF]: {
    calculation: (price: number) => price - price * 0.25,
    code: "1557",
    purchaseAmount: 1,
  },
  [KruidvatDealType.THIRTY_PERCENT_OFF]: {
    calculation: (price: number) => price - price * 0.3,
    code: "1064",
    purchaseAmount: 1,
  },
  [KruidvatDealType.THIRTY_PERCENT_OFF_WITH_CARD]: {
    calculation: (price: number) => price - price * 0.3,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDkwM3xpbWFnZS9wbmd8YURaaEwyaGxNQzh6TXpneE1qTTFORFUyTkRFeU5nfGEwMTk2OGY1Y2MyYmM3ZThiZjI1NGIzZThiZGM1NjVjOGRiZDhmNmU0ZmQzNGM2Mzg4NTJlODUzNjgwMTM4Y2M",
    purchaseAmount: 1,
    requiresCard: true,
  },
  [KruidvatDealType.THIRTY_THREE_PERCENT_OFF]: {
    calculation: (price: number) => price - price * 0.33,
    code: "1193",
    purchaseAmount: 1,
  },
  [KruidvatDealType.THIRTY_FIVE_PERCENT_OFF]: {
    calculation: (price: number) => price - price * 0.35,
    code: "1065",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOURTY_PERCENT_OFF]: {
    calculation: (price: number) => price - price * 0.4,
    code: "1067",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOURTY_PERCENT_OFF_WITH_CARD]: {
    calculation: (price: number) => price - price * 0.4,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDg1MXxpbWFnZS9wbmd8YURaa0wyaGtaQzh6TXpneE1qTTFORFl5T1RZMk1nfGJiNTBjYWE2NTFiMzY2MTU2MjY1N2NjMjA5YzQ4OGY3NjcxZmJhNjE2OGNhYzA5YjdjYWZiM2ZmYTg4ODUwYjU",
    purchaseAmount: 1,
    requiresCard: true,
  },
  [KruidvatDealType.FIFTY_PERCENT_OFF]: {
    calculation: (price: number) => price * 0.5,
    code: "1068",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FIFTY_PERCENT_OFF_WITH_CARD]: {
    calculation: (price: number) => price * 0.5,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDkzOXxpbWFnZS9wbmd8YUdGaUwyaGtZeTh6TXpneE1qTTFORFk1TlRFNU9BfDdhZDlkOGQ2ZDE5ZGJkYzAwZjVjMGM5ZjQ1NWU1Mzk0NTEzZjFmMjk4ZTAzN2QwMDRlMWFhMWM5NTY1ZTVkZWU",
    purchaseAmount: 1,
    requiresCard: true,
  },
  [KruidvatDealType.FIFTY_FIVE_PERCENT_OFF]: {
    calculation: (price: number) => price * 0.55,
    code: "1131",
    purchaseAmount: 1,
  },
  [KruidvatDealType.SIXTY_PERCENT_OFF]: {
    calculation: (price: number) => price - price * 0.6,
    code: "1133",
    purchaseAmount: 1,
  },
  [KruidvatDealType.SIXTY_ONE_PERCENT_OFF]: {
    calculation: (price: number) => price - price * 0.61,
    code: "4970",
    purchaseAmount: 1,
  },
  [KruidvatDealType.SEVENTY_FIVE_PERCENT_EXTRA_OFF]: {
    calculation: (price: number) => price - price * 0.75,
    code: "1450",
    purchaseAmount: 1,
  },
  [KruidvatDealType.EIGHTY_PERCENT_OFF]: {
    calculation: (price: number) => price - price * 0.8,
    code: "1500",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FIFTY_PERCENT_OFF_BY_5]: {
    calculation: (price: number) => price * 0.5,
    code: "5489",
    purchaseAmount: 5,
  },
  [KruidvatDealType.ALL_FOR_0_99_EACH]: {
    calculation: () => 0.99,
    code: "1085",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_1_EACH]: {
    calculation: () => 1,
    code: "1086",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_1_29_EACH]: {
    calculation: () => 1.29,
    code: "1411",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_1_50_EACH]: {
    calculation: () => 1.5,
    code: "1088",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_1_99_EACH]: {
    calculation: () => 1.99,
    code: "1089",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_2_EACH]: {
    calculation: () => 2,
    code: "1090",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_2_EACH_DUPLICATE]: {
    calculation: () => 2,
    code: "1296",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_2_50_EACH]: {
    calculation: () => 2.5,
    code: "1415",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_2_99_EACH]: {
    calculation: () => 2.99,
    code: "1092",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_3_EACH]: {
    calculation: () => 3,
    code: "1093",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_3_49_EACH]: {
    calculation: () => 3.49,
    code: "1074",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_3_99_EACH]: {
    calculation: () => 3.99,
    code: "1412",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_4_EACH]: {
    calculation: () => 4,
    code: "1095",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_4_50_EACH]: {
    calculation: () => 4.5,
    code: "1324",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_4_99_EACH]: {
    calculation: () => 4.99,
    code: "1096",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_4_99_EACH_DUPLICATE]: {
    calculation: () => 4.99,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8MTUxOTV8aW1hZ2UvcG5nfGFEbGpMMmhsWlM4ek1EUTJPVEk0TnpFNE1qTTJOZ3wzZjQ1ZTk2MDJkMDMxZTE4YWNmZjc2ZmNjZWRiNmZiZTNiOTkwZTE0MzQ2MDJjMTY5MDUxOTMzOThjMjg1ZmMz",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_5_EACH]: {
    calculation: () => 5,
    code: "1097",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_6_EACH]: {
    calculation: () => 6,
    code: "1100",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_6_50_EACH]: {
    calculation: () => 6.5,
    code: "1366",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_7_EACH]: {
    calculation: () => 7,
    code: "1101",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_7_EACH_DUPLICATE]: {
    calculation: () => 7,
    code: "1265",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_7_49_EACH]: {
    calculation: () => 7.49,
    code: "1102",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_7_50_EACH]: {
    calculation: () => 7.5,
    code: "1103",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_7_99_EACH]: {
    calculation: () => 7.99,
    code: "1104",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_7_99_EACH_DUPLICATE]: {
    calculation: () => 7.99,
    code: "1080",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_8_EACH]: {
    calculation: () => 8,
    code: "1139",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_8_99_EACH]: {
    calculation: () => 8.99,
    code: "1407",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_9_EACH]: {
    calculation: () => 9,
    code: "1107",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_9_49_EACH]: {
    calculation: () => 9.49,
    code: "1413",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_9_99_EACH]: {
    calculation: () => 9.99,
    code: "1109",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_10_EACH]: {
    calculation: () => 10,
    code: "1110",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_11_99_EACH]: {
    calculation: () => 11.99,
    code: "1310",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_12_EACH]: {
    calculation: () => 12,
    code: "1180",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_12_50_EACH]: {
    calculation: () => 12.5,
    code: "1368",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_12_99_EACH]: {
    calculation: () => 12.99,
    code: "1147",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_13_EACH]: {
    calculation: () => 13,
    code: "1399",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_13_99_EACH]: {
    calculation: () => 13.99,
    code: "1469",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_14_99_EACH]: {
    calculation: () => 14.99,
    code: "1231",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_15_EACH]: {
    calculation: () => 15,
    code: "1112",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_16_99_EACH]: {
    calculation: () => 16.99,
    code: "1431",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_17_99_EACH]: {
    calculation: () => 17.99,
    code: "1493",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_18_99_EACH]: {
    calculation: () => 18.99,
    code: "1319",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_19_99_EACH]: {
    calculation: () => 19.99,
    code: "1150",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_20_EACH]: {
    calculation: () => 20,
    code: "1114",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_24_99_EACH]: {
    calculation: () => 24.99,
    code: "1490",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_26_99_EACH]: {
    calculation: () => 26.99,
    code: "1481",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_29_99_EACH]: {
    calculation: () => 29.99,
    code: "1115",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_34_99_EACH]: {
    calculation: () => 34.99,
    code: "1455",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_36_99_EACH]: {
    calculation: () => 36.99,
    code: "1491",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_38_99_EACH]: {
    calculation: () => 38.99,
    code: "1507",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_39_99_EACH]: {
    calculation: () => 39.99,
    code: "1425",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_49_99_EACH]: {
    calculation: () => 49.99,
    code: "1453",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_99_99_EACH]: {
    calculation: () => 99.99,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8MTY2MzJ8aW1hZ2UvcG5nfGFEaGxMMmd4TUM4ek1qRTJNalUyTURBNE1UazFNQXxiNDQxZjdhNWM3OTkxMzA2ZjBjYmJlZGFiMGQ5NDI0MjUwZWJjMzJmNmY0MTZjMjAwNzc3NzJiNjI4YThmZTY1",
    purchaseAmount: 1,
  },
  [KruidvatDealType.ALL_FOR_5_PER_PACK]: {
    calculation: () => 5,
    code: "1175",
    purchaseAmount: 1,
  },
  [KruidvatDealType.SECOND_FOR_ONE]: {
    calculation: (price: number) => (price + 1) / 2,
    code: "1038",
    purchaseAmount: 2,
  },
  [KruidvatDealType.SECOND_FOR_TWO]: {
    calculation: (price: number) => (price + 2) / 2,
    code: "1228",
    purchaseAmount: 2,
  },
  [KruidvatDealType.SECOND_HALF_PRICE]: {
    calculation: (price: number) => price * 0.75,
    code: "1039",
    purchaseAmount: 2,
  },
  [KruidvatDealType.SECOND_FOR_60_PERCENT_OFF]: {
    calculation: (price: number) => (price + price * 0.4) / 2,
    code: "1525",
    purchaseAmount: 2,
  },
  [KruidvatDealType.SECOND_HALF_PRICE_DUPLICATE]: {
    calculation: (price: number) => price * 0.75,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDYzNHxpbWFnZS9wbmd8YURVeEwyZzRNUzh4TkRrME56UTNNalUzTWpRME5nfDBjOGI1YjYxMDBkMWE1YzIzMGFkMGY3OTQyODNiYjQ0N2YxYzJhMDI4ZWJmZGI2OWI1MzBhOWU1YTY3MjkyZGY",
    purchaseAmount: 2,
  },
  [KruidvatDealType.SECOND_HALF_PRICE_WITH_CARD]: {
    calculation: (price: number) => price * 0.75,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDUyM3xpbWFnZS9wbmd8YURsakwyaGtOaTh6TXpneE1qTTFORGd5TmpJM01BfDRiNDQ2YTljNDMyZWU5YjE4YzkyZGE2NGMyMzhlMjI3NDUxMDZkMGQ5NzVmNjRhZTc0NjM0MTkyOTgxNzllYWI",
    purchaseAmount: 2,
    requiresCard: true,
  },
  [KruidvatDealType.ONE_OFF]: {
    calculation: (price: number) => price - 1,
    code: "1001",
    purchaseAmount: 1,
  },
  [KruidvatDealType.TWO_OFF]: {
    calculation: (price: number) => price - 2,
    code: "1004",
    purchaseAmount: 1,
  },
  [KruidvatDealType.THREE_OFF]: {
    calculation: (price: number) => price - 3,
    code: "1040",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOUR_OFF]: {
    calculation: (price: number) => price - 4,
    code: "1051",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FIVE_OFF]: {
    calculation: (price: number) => price - 5,
    code: "1055",
    purchaseAmount: 1,
  },
  [KruidvatDealType.SIX_OFF]: {
    calculation: (price: number) => price - 6,
    code: "1187",
    purchaseAmount: 1,
  },
  [KruidvatDealType.EIGHT_OFF]: {
    calculation: (price: number) => price - 8,
    code: "1331",
    purchaseAmount: 1,
  },
  [KruidvatDealType.NINE_OFF]: {
    calculation: (price: number) => price - 9,
    code: "1356",
    purchaseAmount: 1,
  },
  [KruidvatDealType.TEN_OFF]: {
    calculation: (price: number) => price - 10,
    code: "1057",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FIFTEEN_OFF]: {
    calculation: (price: number) => price - 15,
    code: "1251",
    purchaseAmount: 1,
  },
  [KruidvatDealType.TWENTY_OFF]: {
    calculation: (price: number) => price - 20,
    code: "1179",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_0_89_WITH_CARD]: {
    calculation: () => 0.89,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8Mzk0NHxpbWFnZS9wbmd8YUdJekwyaGxaaTh6TkRReU5URXpOelU1TkRNNU9BfDBjMWQ0ZjNhNDQ1NmFmOTI2YjNiZjdhNTZiN2I2YTZiZjIwZTcwYzMyZTUzY2QzZTNjMjY0OTBlZjIzYTYzOGY",
    purchaseAmount: 1,
    requiresCard: true,
  },
  [KruidvatDealType.FOR_0_99]: {
    calculation: () => 0.99,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDE1M3xpbWFnZS9wbmd8YURabEwyZzBNeTh6TXpnMU1EQTJOVGM0TURjMk5nfDA3NDQyNTA3OTBjMmY3YjRiMjdlNTE2YTBiY2NlMTg5M2Q4YzM4YjAwMzhhYjM3YjZjZDg2MWZkOTc1ZTJkM2U",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_1_49]: {
    calculation: () => 1.49,
    code: "4169",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_1_50_WITH_CARD]: {
    calculation: () => 1.5,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDEyN3xpbWFnZS9wbmd8YUdGbEwyZ3dNaTh6TXpneE1qTTFOamcxTnpnNE5nfDUwZTc1ODkyZDVlMDFiZGVhZmI3YmJhY2U2MTAzNWRkZTE1YzJmZTNlYTA0Y2NlMmY3NmYwYTQwMTlhYmM1NDg",
    purchaseAmount: 1,
    requiresCard: true,
  },
  [KruidvatDealType.FOR_1_99_WITH_CARD]: {
    calculation: () => 1.99,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDEyN3xpbWFnZS9wbmd8YURKaEwyZ3daQzh6TXpneE1qTTFOalV6TURJd05nfDRiNDYwMjQyZWEzZGI4M2RhMjE5ZThmNzE2NGFjZmIwODM0YTE0N2FhZGRlMDhiY2IwNGFhZjczNWE5ZmQxNzQ",
    purchaseAmount: 1,
    requiresCard: true,
  },
  [KruidvatDealType.FOR_2_75]: {
    calculation: () => 2.75,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDA4MXxpbWFnZS9wbmd8YURreUwyZzVNUzh6TURnM09EYzJNalEyTnpNMU9BfDM2MGRhNDYyMWMyZTg4M2RmMGQ5NmY5NmViYWQyZWU2NTZkMzMzNjU0MjExZmMxMTEwZWMyMTQ2YzQzMWFhZmY",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_2_99]: {
    calculation: () => 2.99,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDI1NnxpbWFnZS9wbmd8YUROa0wyaGtaaTh6TWpRMk16UTFNamt6TURBM09BfGMzNjg1YmZiZjcwNjM0OTYzYjQ4NTJhMWNiNjFlMzc1MWI4NmU0Nzk2OGM5MTJkMDU3NzYzNjljOTRkZDA3OWI",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_3]: {
    calculation: () => 3,
    code: "4227",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_3_WITH_CARD]: {
    calculation: () => 3,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8Mzc4MXxpbWFnZS9wbmd8YUdGbUwyaGpNaTh6TkRVd05UUXlNak0zTWpnNU5BfGU2OTJkNzc4YWQ5MTExNjQ5OWM3MTNmMGJhM2M3ZGNlOWIwZjk5NjU5MmY4NzcwMjllYTRkYzhkMDM1MTMxYzA",
    purchaseAmount: 1,
    requiresCard: true,
  },
  [KruidvatDealType.FOR_3_99]: {
    calculation: () => 3.99,
    code: "4149",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_4]: {
    calculation: () => 4,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDEzNnxpbWFnZS9wbmd8YURGa0wyZzJOQzh6TWpNM05qRXpNVFV4T0RRNU5BfDAwMDUxYThhODAyOTJjNGE2ZWM2OTkxMzY0MDA3YzIxOTcwODk0NTg5ZDg4Zjk4NDEwZTdmMmJiM2IxNjhmMTI",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_4_39]: {
    calculation: () => 4.39,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDMzNHxpbWFnZS9wbmd8YURObEwyZzBZUzh6TXpnMU1EQTJOVFU0TkRFMU9BfDY3OWMzMDE5MWE0OTgyZDM2NTk2MjEzYWVkMjMwMjE3NGVlMzk2YzAxNWEwMWNlNzAzMWZmMmZhZTgzZjBkMWU",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_4_99]: {
    calculation: () => 4.99,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDE3N3xpbWFnZS9wbmd8YUdGbEwyZzJZaTh6TWpNM05qRXpNVGM0TURZek9BfDU0ODQxNDlhOWZhNjJmNjQyZmZjYTMyYmJlN2M4N2MzNGVhNTgwMDk3MmUxYTk3OWQwM2Q4ZGEyMzVhZTBiOTg",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_4_99_WITH_CARD]: {
    calculation: () => 4.99,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDEwMnxpbWFnZS9wbmd8YURreEwyZzNaQzh6TXpneE1qTTFOVE0xTURVMU9BfDFiODQ3N2NlNjk3YWRmYzI3NjYwODgwYjQ1MzZmMDhlMDFmNjk3MjljNTgwNmJhZmZiOGY5YWNkNGUwYjIwYjU",
    purchaseAmount: 1,
    requiresCard: true,
  },
  [KruidvatDealType.FOR_5]: {
    calculation: () => 5,
    code: "4190",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_5_49]: {
    calculation: () => 5.49,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDI5MnxpbWFnZS9wbmd8YURNMEwyZzRPQzh6TkRBMU1ERXpPVFUxTXpneU1nfDgyYzYyZTk5MDM4M2YwMDJhYmU5ZGM1OGZjMWI3MDljMTE2NTJiZGI5MGVhMDk4YzY4NmYxNjA3Mjg1MDE1MjM",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_5_75]: {
    calculation: () => 5.75,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDE1OXxpbWFnZS9wbmd8YURRekwyaGpPQzh6TkRFeU1qYzVNalUyTmpneE5BfDRhY2E1Mzg1MzJlNWQ5NDQ3MjIzNTI3OWU3NDQ5NjVmMTk0NDIzYjQyYjBmZjUwMmQ5MmYwNmIyNWZjM2EwYzE",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_5_99]: {
    calculation: () => 5.99,
    code: "4198",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_6]: {
    calculation: () => 6,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDE2OHxpbWFnZS9wbmd8YURjd0wyZzBZUzh6TWpFNE16UTRNamswTVRRM01BfGJjN2E4ZjI4OTZkZDQzNGVkZWI3NGUwYzEyMzc1MDViYWQzNGY1MzFmOTFkZjliZDAzNzE1NmZkM2QzZTcxNjc",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_6_49]: {
    calculation: () => 6.49,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDMzNXxpbWFnZS9wbmd8YURCbEwyaGxOaTh6TWpRMk16UTFNamN6TXpRM01BfDI0M2E3ZTczMzRlZDAyZTJkZjEwZGYzY2FjNjRjMDRjYjI2NGJiMDJhMDU1N2I3NzlkMjZiOTI0ZjFiY2U5ODY",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_6_99]: {
    calculation: () => 6.99,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDMwMXxpbWFnZS9wbmd8YURneUwyZzRZaTh6TWpjeE16TTFOVEEyTnpReU1nfGYxMmUxZGMwMmIwMWY2MWNmNGZhZjk3MTg3Y2E4MDE3MjEwMDFlNDhlMDhiZjEzZDhiYWE2YzI2ZGI4YzYyNDM",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_7_50]: {
    calculation: () => 7.5,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDEwMHxpbWFnZS9wbmd8YURrMkwyaGtNUzh6TWpnek56a3dNalEyTnpFd01nfDAxMTA4NGQzOGY5YmE1YWNhMjFkNTNhODViNjAzYmIyYjU5Nzk2OTEyNDc4YmMxNmZkZmRjZjQyZmEyOTkyYjg",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_7_99]: {
    calculation: () => 7.99,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDE2OHxpbWFnZS9wbmd8YURReUwyZ3pOQzh6TWpJME1qazJPVFEzTnpFMU1BfDM5NTRlYmExNTYyN2YwZmE5YjI0NTk0YTA2NDE5YTc0ZjViMDRkZDY5ZTk0MWY4NWFiYTdkMzc5ZmM0Yzc2YzE",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_8]: {
    calculation: () => 8,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDI0OXxpbWFnZS9wbmd8YUdOa0wyaGxPUzh6TWpRMk16UTFNall3TWpNNU9BfGIyNDBiODcwZjUzMWQyY2FmM2FlNmVkN2ZmMTg0ODI2YTcyOWVhOTJlYTEwMjdjZmM5ZjY5YjlhOTYwOTQ2YTQ",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_9]: {
    calculation: () => 9,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDIxNHxpbWFnZS9wbmd8YURoakwyZzRPQzh6TXpBMU56YzNNRGN6TXpVNU9BfDY4ODBmNzE5ODljMjQ0MzUwODgwZjc4YjgzNWVmYzIxNDQxMGZmYjAwZjM3YTNkYmQ5MjU4NWNiOTVhYmNlNzQ",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_9_99]: {
    calculation: () => 9.99,
    code: "4202",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_9_99_WITH_CARD]: {
    calculation: () => 9.99,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8MzgxN3xpbWFnZS9wbmd8YURjd0wyaGpNeTh6TkRVd05UUXlNak13TnpNMU9BfDQ2ZjJlYzY5YzU1NTc3NzRjYzE3N2NiMGYwYzMwOTdhNDMyMzgxNDY1YmZhNDc4Y2Q0NGZjZGY2MDc1NjRhMjc",
    purchaseAmount: 1,
    requiresCard: true,
  },
  [KruidvatDealType.FOR_10]: {
    calculation: () => 10,
    code: "4494",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_10_WITH_CARD]: {
    calculation: () => 10,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDI3MHxpbWFnZS9wbmd8YUdRMEwyZzNOaTh6TXpneE1qTTFOVFUwTnpFMk5nfGM0NWI3N2MyZDE1NTU2ZWE0YWRjMDBhODE2YzFkZDE5Mzk2NzExMDEyNDc1YTQwYTdjNDQ0ZjVjZmFkNDY1YzU",
    purchaseAmount: 1,
    requiresCard: true,
  },
  [KruidvatDealType.FOR_10_49]: {
    calculation: () => 10.49,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDY2NHxpbWFnZS9wbmd8YUdaakwyaGlOeTh6TkRjek56a3pNalF6TlRRNE5nfDY1ZDAzNWJhNjk0ZGI1NTA0YWUwYWU4YzJkMTdlYTBhMzZiYjQyNjgzNTdiODQ4NjgwYjdhNWEwNTNmM2VlNWY",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_11_99]: {
    calculation: () => 11.99,
    code: "4347",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_12]: {
    calculation: () => 12,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDUzNXxpbWFnZS9wbmd8YURaakwyZzNNaTh6TWpNM05qRXpNVGszTnpJME5nfDZhNjllNTdhODAwODQ5Y2NmODAzZTM1MTQ5NTliZDEyMjFjM2VhMjE3ZjFlYWE3Y2I0MDhiYWIxNTE4MzUwOTg",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_12_50]: {
    calculation: () => 12.5,
    code: "4610",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_13]: {
    calculation: () => 13,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDU0MHxpbWFnZS9wbmd8YURCaEwyZ3hOaTh6TVRFeE5UTTBORGN3TnpZeE5BfDQ3YmM3NWY0NDQyZmJiYjI1ZmEwYmNlMGFhZThhNDlkZWI0NTZlNTJhMTdjMjFhZWI5YmY5MzM3ZTk0YTFiNTY",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_13_95]: {
    calculation: () => 13.95,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDYyMXxpbWFnZS9wbmd8YURGbUwyaGxPUzh6TWpRMk16UTFNalkyTnprek5BfDg3NzJjOWJlODUxYWI2ZGJkMWY0YmIwY2Q1NjExZmJhZTBlNjkzZDAzNDgwMmRmNzQzNTk3NDMyN2YyM2UzN2E",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_14]: {
    calculation: () => 14,
    code: "4494",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_14_99]: {
    calculation: () => 14.99,
    code: "4499",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_14_99_WITH_CARD]: {
    calculation: () => 14.99,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NjIwM3xpbWFnZS9wbmd8YUdFMUwyaGxPQzh6TXpjeE56azBOVEEzTXpZNU5BfDBjZjFiYTBkMWE0Zjk5OGJmMTBlYzJlZTRhNjZiMmVjM2M2OTZkMzA2YWI4NmMzN2UxMWYzOTZkMDNhOGE1MDA",
    purchaseAmount: 1,
    requiresCard: true,
  },
  [KruidvatDealType.FOR_15]: {
    calculation: () => 15,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDUwNHxpbWFnZS9wbmd8YURnMEwyZzVOQzh6TWpZM016VXdNREUyT0RJeU1nfDVhZTA0YzRkZjAxNjNlMmVjNGM5YmU0ZmEzNTA1ZGI1MGUzOWZmZGJhMDQwYWQxZjIzZjQ2YjA0YzZkOGRjYjg",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_15_99]: {
    calculation: () => 15.99,
    code: "4525",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_17]: {
    calculation: () => 17,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDM5M3xpbWFnZS9wbmd8YURVekwyZ3pOeTh6TWpJME1qazJPVFUwTWpZNE5nfDk5ZjI5NTExNTE3YmY3YjhjYjYwODYzMzYwZmQ5NTE4NzUyNWI4MGYzOWMwNDYyZTExZDgxNzQ5YzEyYjRiMmM",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_17_49]: {
    calculation: () => 17.49,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDQyOXxpbWFnZS9wbmd8YURReUwyZzVaUzh5TnpJME9UQXhORGd6TXpFNE1nfDA0MDhhZDc1YjAzOTgzMDQ2ZTkzMjVmNWQ1YWMxNGY0NWQyY2E1YTRlMmUyYjllYTgwN2M4MDI1NjQxMDkwNGI",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_17_99]: {
    calculation: () => 17.99,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDM5N3xpbWFnZS9wbmd8YUdNMUwyZzVNQzh6TWpZM016VXdNREF6TnpFMU1BfDM0NTRlYmQ0OTczZDNjYzdkMmEzODk5YmU2OGExZjc2YmYwNTZkYmQwZDBlYjU3YTBiN2Q2ZTIwNjVkZWEwNmU",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_19_99]: {
    calculation: () => 19.99,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDUyOHxpbWFnZS9wbmd8YUdSakwyaGxaaTh6TWpRMk16UTFNalEzTVRNeU5nfGExYTFiMTMzYjRmNDFlOTU5ZWFmOGI3ZWM1N2FjOGE2MzI2ZGVlODExMTRjMTJjZTk3YjA4MjFmY2EyZWNiN2E",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_19_99_WITH_CARD]: {
    calculation: () => 19.99,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDI3MHxpbWFnZS9wbmd8YURaa0wyZ3dOaTh6TXpneE1qTTFOamN5TmpneE5BfDIwOGRiMzVjNDE4YzgyMzE3ZWFiMDYxYWJlODMzNjJlZDNhZGYzMGRhYzQ4NDA3OTRkOWQ0NmI1YzYxYzI2YTM",
    purchaseAmount: 1,
    requiresCard: true,
  },
  [KruidvatDealType.FOR_24_50]: {
    calculation: () => 24.5,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDcxMHxpbWFnZS9wbmd8YURVMEwyaG1OUzh6TXpFME1qSXdPVFUwTkRJeU1nfDUyZTEyZTE3YTQ2NjhmYjFkMjMyMzAzYTcxMTFjNmRlZDczNTk1NmMyMjQwMmY5Yzc0YjlmZjAwMzVlNTg0YzU",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_24_99]: {
    calculation: () => 24.99,
    code: "4626",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_24_99_WITH_CARD]: {
    calculation: () => 24.99,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDAxNXxpbWFnZS9wbmd8YUdZeEwyaGlZaTh6TkRVd05UUXlNalUyT1RVd01nfDBlOWM2OTY1NmMxZTc1OGMxODRjMjkwZjc4MGY5M2IyMGY4OWI1Zjk3YWE2M2IyZjljMTIwZWM3ZjFiODI0ZTk",
    purchaseAmount: 1,
    requiresCard: true,
  },
  [KruidvatDealType.FOR_25]: {
    calculation: () => 25,
    code: "4628",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_26_50]: {
    calculation: () => 26.5,
    code: "4765",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_29_99]: {
    calculation: () => 29.99,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8MHxhcHBsaWNhdGlvbi9vY3RldC1zdHJlYW18YUdJeEwyaG1NaTh6TkRReU5URXpOelkxT1Rrek5BfDkyZDczOTI4Zjk2YjdiNzY1NTE0ZjBjNThhZDRhM2JhMDA3MWVhMzVlNzBhM2FiYWU0MmQxODFiNmM5YWU3ODk",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_32_99]: {
    calculation: () => 32.99,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDY0NXxpbWFnZS9wbmd8YURBekwyZzVaaTh6TWpRNU9USTJORGc0TURZM01BfDUxNmFiNTY5MDkxOWY2MWQ1OTRkYmE0NThmNDdjZDA0MmM2ZTIxM2YzYzNkNjVlMWM3NjI0MzEzYjhiNDlmNjY",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_33_99]: {
    calculation: () => 33.99,
    code: "1647",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_35]: {
    calculation: () => 35,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDY0NHxpbWFnZS9wbmd8YUdSbEwyZzROeTh6TXpBMU56YzNNRGM1T1RFek5BfGI0NzdlNzFlNzNjNjE3MzEzN2E2ZTY2YTcxNzg0ZTU2ZDcxNDc1YzEwZWIyMTM3OTIyYTM3Y2Y5OTVhMjcyOGM",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FPR_44_99]: {
    calculation: () => 44.99,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDM2MXxpbWFnZS9wbmd8YUdGa0wyZzJaUzh6TWpNM05qRXpNVGcwTmpFM05BfDlmZjg2ZTk2OWM4YjE3Mjk0MWUxMmQwMTU5Yzg0OTAzMDg1ZDA2YTQ5ZDEwZTQzMzcxYjU1NWYzZGRiOTA0MjE",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FPR_45]: {
    calculation: () => 45,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDYwOHxpbWFnZS9wbmd8YURRMEwyZ3paUzh6TkRjMU1UY3hNall5TkRZM01BfGMxNTE5YzhiOTNhYjQ0ODgwMTBiYzdhNGY5MTI4NTJjODUzZTRmYjdiYmI0YTI4ZjcyNWNlYzhmNmIzNmUzNmI",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FPR_45_99]: {
    calculation: () => 45.99,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDQ1NXxpbWFnZS9wbmd8YURreEwyZ3pZeTh4TmpNeE1qazBNamc0TmprME1nfGNlMzI4ZGFiODM5NmMwN2NjY2ZiNzNiYzI3ZmM0YjU3OTVmOGQ3NDM2Zjk1ZWQ2ZGM1ZDg0NWJjNWZhYWZhNDQ",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_47_99]: {
    calculation: () => 47.99,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDM4OXxpbWFnZS9wbmd8YURNeEwyZ3hOQzh6TXpReU5UazFOekkxTnpJME5nfDYzNjZmZGRlODRkYTdhODE2MzEwNWYxZDk5ZTkzMWE4YzhhZDJmNmMyYzc1NDBlY2Y0YzI1YTQ0OWQ3MTdjOTU",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_54_99]: {
    calculation: () => 54.99,
    code: "4432",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_59_99]: {
    calculation: () => 59.99,
    code: "4467",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_69_99]: {
    calculation: () => 69.99,
    code: "4590",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_87_49]: {
    calculation: () => 87.49,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NDYwN3xpbWFnZS9wbmd8YURNMEwyZ3pZaTh6TkRjMU1UY3hNalUxT1RFek5BfDU4MWNlM2IyYzc2ODNlZDI3YTBlNjI3YTQ5MGEyM2FiNDc3NzJkODBjZDEzYjgxZjdiOWUxMDg5M2M2OTk2NDM",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_89_99]: {
    calculation: () => 89.99,
    code: "4597",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_129_99]: {
    calculation: () => 129.99,
    code: "4496",
    purchaseAmount: 1,
  },
  [KruidvatDealType.FOR_249_99]: {
    calculation: () => 249.99,
    code: "4605",
    purchaseAmount: 1,
  },
  [KruidvatDealType.STACK_25_PERCENT_AT_3]: {
    calculation: (price: number) => price - price * 0.25,
    code: "1656",
    purchaseAmount: 3,
  },
  [KruidvatDealType.STACK_40_PERCENT_AT_3]: {
    calculation: (price: number) => price - price * 0.4,
    code: "1343",
    purchaseAmount: 3,
  },
  [KruidvatDealType.STACK_60_PERCENT_AT_3]: {
    calculation: (price: number) => price - price * 0.6,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NTYyNnxpbWFnZS9wbmd8YURrNEwyaG1ZUzh5T1RReU9UZ3hNemN6T1RVMU1BfDY1MDRkMjhlMjgyYzNjYTk3ZGI5YzE2NDJhMzM1OWUxYWJkNDQ0MjhkMjZiYjZlZTc4Njk0OTI2M2U1NmM1MjI",
    purchaseAmount: 3,
  },
  [KruidvatDealType.STACK_15_PERCENT_AT_4]: {
    calculation: (price: number) => price - price * 0.15,
    code: "bWFzdGVyfHByb21vdGlvbi1sYWJlbHN8NTYwNXxpbWFnZS9wbmd8YURJekwyaGxOUzh6TkRReU5URXpOekkyTmpjeE9BfGQ3NjgyNzAwNTFiYWY2ZDkzOTUxODcyM2ViN2VkMjBjZWYxOGE0YWIxZDA1Nzc2OWM3MmI4ODFkODcwZTU0ZGQ",
    purchaseAmount: 4,
  },
});
