name: Deals CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  audit:
    name: Audit dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm audit --omit=dev

  get_sha:
    name: Get short SHA for image tags
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.get_sha.outputs.sha_short }}
    steps:
      - uses: actions/checkout@v4
      - id: get_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  determine_buildable:
    name: Determine buildable apps
    runs-on: ubuntu-latest
    outputs:
      buildable: ${{ steps.determine_buildable.outputs.buildable }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - id: determine_buildable
        run: echo "buildable=$(bun run determine-buildable)" | tr / - >> $GITHUB_OUTPUT

  determine_testable:
    name: Determine testable apps
    runs-on: ubuntu-latest
    outputs:
      testable: ${{ steps.determine_testable.outputs.testable }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - id: determine_testable
        run: echo "testable=$(bun run determine-testable)" >> $GITHUB_OUTPUT

  lint:
    name: Static code analysis
    needs: audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run lint

  test:
    name: Unit tests
    needs: [audit, determine_testable]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: ${{fromJson(needs.determine_testable.outputs.testable)}}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: npm ci
      - run: bun run test ${{matrix.app}}

  build-image:
    name: Build image
    needs: [audit, determine_buildable]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: ${{fromJson(needs.determine_buildable.outputs.buildable)}}
    steps:
      - uses: actions/checkout@v4
      - run: docker compose build ${{matrix.app}}
      - run: docker save -o ${{matrix.app}}-image.tar ghcr.io/ionaru/deals/${{matrix.app}}:latest
      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.app}}-image
          path: ${{matrix.app}}-image.tar
          retention-days: 1

  e2e:
    # Loads all docker images from the build-image job and runs e2e tests against a fully local stack.
    name: E2E tests
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - run: for f in */*.tar; do docker load -i $f; done
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: docker compose --file apps/client-e2e/compose.yaml up --wait -d
      - run: docker compose pull nats
      - run: docker compose up --pull=never --no-build --wait -d
        env:
          STORAGE_DB_HOST: mysql
          STORAGE_DB_PORT: 3306
          STORAGE_DB_USER: e2e
          STORAGE_DB_PASS: DontTellAnyoneThisPassword
          STORAGE_DB_SSL: false
          STORAGE_DB_NAME: deals_e2e
          STORAGE_DB_SYNCHRONIZE: true
          GATEWAY_SESSION_NAME: DealE2ESession
          GATEWAY_SESSION_SECRET: DontTellAnyoneThisSecret
          DEALS_CLIENT_PORT: 4200
          AUTH_DB_URL: "mongodb://e2e:DontTellAnyoneThisPassword@mongo"
          AUTH_DB_NAME: E2E-Deals-Auth
          SESSION_DB_NAME: E2E-Deals-Session
      - run: npm ci
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: npx nx run client-e2e:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: dist/cypress/apps/client-e2e/screenshots
          retention-days: 1
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: dist/cypress/apps/client-e2e/videos
          retention-days: 1
          if-no-files-found: ignore
      - run: docker compose logs --no-color >& e2e.log
        if: always()
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-docker-logs
          path: e2e.log
          retention-days: 1

  push-image:
    name: Push image
    needs: [lint, test, e2e, get_sha, determine_buildable]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{fromJson(needs.determine_buildable.outputs.buildable)}}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{matrix.app}}-image
      - run: docker load -i ${{matrix.app}}-image.tar
      - run: docker tag ghcr.io/ionaru/deals/${{matrix.app}}:latest ghcr.io/ionaru/deals/${{matrix.app}}:${{needs.get_sha.outputs.sha_short}}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker push -a ghcr.io/ionaru/deals/${{matrix.app}}

  deploy:
    needs: [get_sha, push-image]
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          command_timeout: 30m
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SECRET }}
          script: |
            cd /home/${{ secrets.DEPLOY_USER }}/apps/deals
            git fetch -a
            git switch -d ${{needs.get_sha.outputs.sha_short}}
            DEALS_BUILD_TAG=${{needs.get_sha.outputs.sha_short}} docker compose pull
            DEALS_BUILD_TAG=${{needs.get_sha.outputs.sha_short}} docker compose up --pull=never --no-build --wait -d
