name: Deals CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm audit --omit=dev

  get_sha:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.get_sha.outputs.sha_short }}
    steps:
      - uses: actions/checkout@v4
      - id: get_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  lint:
    needs: audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run lint

  test:
    needs: audit
    strategy:
      matrix:
        app: [auth]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: npm ci
      - run: bun run test ${{matrix.app}}

  build-image:
    needs: [lint, test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [auth, gateway, client, scrapers-jumbo, scrapers-kruidvat, storage]

    steps:
      - uses: actions/checkout@v4
      - run: docker compose pull ${{matrix.app}}
      - run: docker compose build ${{matrix.app}}
      - run: docker save -o ${{matrix.app}}-image.tar docker.saturnserver.org/deals/${{matrix.app}}:latest
      - uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.app}}-image
          path: ${{matrix.app}}-image.tar
          retention-days: 1

  push-image:
    needs: [build-image, get_sha]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [auth, gateway, client, scrapers-jumbo, scrapers-kruidvat, storage]

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{matrix.app}}-image
      - run: docker load -i ${{matrix.app}}-image.tar
      - run: docker tag docker.saturnserver.org/deals/${{matrix.app}}:latest docker.saturnserver.org/deals/${{matrix.app}}:${{needs.get_sha.outputs.sha_short}}
      - uses: docker/login-action@v3
        with:
          registry: docker.saturnserver.org
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: docker push -a docker.saturnserver.org/deals/${{matrix.app}}
